init: update, still the lvopen() failure to fix...this looks like an old issue

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $Header: mkinitramfs-ll/init,v 0.6.0 2012/05/15 15:07:05 -tclover Exp $
+# $Header: mkinitramfs-ll/init,v 0.6.0 2012/05/16 02:07:18 -tclover Exp $
 #
 # WARNING: USE AT YOUR OWN RISK!
 # NEED SOME HELP? WHERE'S THE README FILE? YOU ASK? WHO KNOWS.
@@ -15,18 +15,25 @@ gv_splashd=1
 gv_splash=verbose
 gv_shrl=0
 # functions
-info() 	{ echo -ne "\033[1;32m* \033[0m$@\n"; }
-warn() 	{ echo -ne "\033[1;33m* \033[0m$@\n"; }
-error() { echo -ne "\033[1;31m* \033[0m$@\n"; }
+info() 	{ echo -ne "\033[1;32m * \033[0m$@\n"; }
+warn() 	{ echo -ne "\033[1;33m * \033[0m$@\n"; }
+error() { echo -ne "\033[1;31m * \033[0m$@\n"; }
+
+debug() {
+	if $@; then echo "[$?]: $@" >> /init.log
+	else echo "[$?]: $@" >> /init.log; return 1; fi
+}
 
 die() {
-	umount -ln /mnt/tok &>/dev/null
+	umount -ln /mnt/tok
 	[ "${gv_splash}" == "silent" ] || verbose
 	error "$@"
 	info "Dropping you into a minimal shell..."
 	for lk in ${gv_lkey}; do dmclose "${lk}"; done
 	for ld in ${gv_ldev}; do losetup -d ${ld}; done
-	exec sh
+	if [ -c "/dev/tty1" ]; then 
+		setsid sh -c "exec sh --login < /dev/tty1 > /dev/tty1 2>&1"
+	else sh --login; fi
 }
 
 bchk() {
@@ -38,7 +45,7 @@ bchk() {
 achk() {
 	if [ -e "/etc/applets" ]; then	
 		for app in $(cat /etc/applets); do 
-			[ -h ${app} ] || /bin/busybox --install -s && break
+			[ -h ${app} ] || busybox --install -s && break
 		done
 	else busybox --install -s
 		info "There's no /etc/applets, installing symlinks."
@@ -67,7 +74,7 @@ silent() { scmd "set mode silent"; }
 smsg() { scmd "set message $@"; scmd "repaint"; }
 
 spalshd_init() {
-	[ ${uv_check_env} ] || bchk "splash_util" "--"
+	[ "${uv_check_env}" ] || bchk "splash_util" "--"
 	[ -n "$(echo ${gv_stty} | grep /dev)" ] || gv_stty="/dev/${gv_stty}"
 	[ -n "${gv_stty}" ] && exec < ${gv_stty} > ${gv_stty} &>/dev/null
 	[ -e /lib/splash/cache ] || mkdir -p /lib/splash/cache
@@ -79,16 +86,18 @@ spalshd_init() {
 splashd_stop() { [ "${gv_splashd}" ] && gv_splashd=1 scmd "exit"; }
 
 ishrl() {
+	debug info "init shell runlevel: ${1}"
 	if [ "${gv_shrl}" == "${1}" ]; then verbose
-		info "Shell runlevel: ${1}"
 		local lv_scr="$(ls /etc/local.d/${1}?-*.sh &>/dev/null)"
 		if [ -n "${lv_scr}" ]; then
 			for scr in ${lv_scr}; do 
 				info "executing ${scr}..."
-				${scr} || warn "${scr} failed"
+				debug ${scr} || warn "${scr} failed"
 			done
 		fi
-		exec sh
+		if [ -c "/dev/tty1" ]; then 
+			setsid sh -c "exec sh --login < /dev/tty1 > /dev/tty1 2>&1"
+		else sh --login; fi
 	fi
 }
 
@@ -237,15 +246,12 @@ dmopen() {
 
 lvopen() {
 	[ "${uv_check_env}" ] || bchk "lvm" "--"
-	info "lvm"
-	if lvchange -ay ${1/-//}; then continue
-	info "$?"
-	elif [ -n "${2}" ]; then
+	debug lvchange -ay ${1/-//}
+	if [ "$?" != "0" ] && [ -n "${2}" ]; then
 		local lv_pv="${2}" IFS="${IFS}:"
 		[ -e "/mnt/tok/${lv_pv}" ] && lv_pv="$(cat /mnt/tok/${lv_pv})"
-		info $lv_pv
-		for pv in ${lv_pv}; do dmopen "${pv}"; done
-		vgchange -ay ${1%-*} &> /dev/null || dmclose "${lv_pv}" "${1}"
+		for pv in ${lv_pv}; do debug dmopen "${pv}"; done
+		debug vgchange -ay ${1%-*} &> /dev/null || dmclose "${lv_pv}" "${1}"
 	else die "${1} require a valid crypted physical volume"; fi
 	if [ -b "/dev/mapper/${1}" ]; then local lv_mapping=/dev/mapper/${1}
 	elif [ -b "/dev/${1/-//}" ]; then local lv_mapping=/dev/${1/-//}
@@ -298,22 +304,21 @@ rootfs() {
 	[ -n "${gbov_mtopt}" ] && local lv_mtopt="-o ${gv_mtopt}"
 	[ -n "${lv_rofs}" ]  && lv_rofs="-t ${lv_rofs}"
 	[ -n "${gv_root}" ] || die "iroot=* arg [PV|VG-LV][:fsck:<fs>] are missing."
-	getkey "${lv_kmod}" "${lv_kdev}" "${lv_kfpt}" "root"
+	debug getkey "${lv_kmod}" "${lv_kdev}" "${lv_kfpt}" "root"
 	ishrl 3d
-	info "ROOT LV..."
 	[ -n "${lv_raid}" ] && mdopen "${lv_raid}"
 	if [ -n "${lv_lvm}" ]; then 
-		local lv_dev=$(lvopen "${lv_root}" "${lv_lvm}")
+		local lv_dev=$(debug lvopen "${lv_root}" "${lv_lvm}")
 	elif [ -n "${gv_cmode}" ]; then info "...encrypted rootfs."
 		dmopen "${uv_root_map:-root}-${gv_root}" 
 		local lv_dev=/dev/mapper/${uv_root_map:-root}
 	else local lv_dev=$(_blkid "${lv_root}"); fi
 	ishrl 3f
-	[ -n "${lv_fsck}" ] && fsck ${lv_rofs} ${lv_dev} 2>/dev/null 
+	[ -n "${lv_fsck}" ] && fsck ${lv_rofs} ${lv_dev} 
 	[ "$?" ] || { [ "${lv_fscf:-${uv_fscf:-y}}" = "y" ] && \
 		die "Failed to fsck rootfs, exit-code: $?"; }
 	ishrl 3m
-	mount ${lv_mtopt} ${lv_rofs} ${lv_dev} /newroot &>/dev/null
+	mount ${lv_mtopt} ${lv_rofs} ${lv_dev} /newroot
 	if [ ! "$?" ]; then
 		if [ -n "${gv_cmode}" ]; then
 			dmclose "${lv_lvm:-${uv_root_map:-root}}" "${lv_lvm:+${lv_root}}"
@@ -336,7 +341,6 @@ swp() {
 	[ -n "$lv_hdev" ] || die "${lv_mapp} dev|VG-LV is missing."
 	[ -n "$lv_type" ] || die "${lv_mapp} type file|swap is missing."
 	[ -n "$lv_sign" ] && lv_sign=:$lv_sign
-	info "SWAP LV..."
 	getkey "${lv_kmod}" "${lv_kdev}" "${lv_kfpt}" "root"
 	[ -n "${lv_raid}" ] && mdopen "${lv_raid}"
 	if [ -n "${lv_lvm}" ]; then 
@@ -351,7 +355,7 @@ swp() {
 }
 
 resume() {
-	[ "${gv_splash}" = "silent" ] || smsg "Resuming..."
+	[ "${gv_splash}" == "silent" ] || smsg "Resuming..."
 	splashd_stop
 	[ -n "$(echo "${gv_toi}"|cut -d':' -s -f2)" ] && {
 :		local ${lv_raid:=$(echo "${gv_raid}" | cut -d',' -f3)}
@@ -361,7 +365,7 @@ resume() {
 	_modprobe tuxonice
 	echo ${gv_dev} > /sys/power/tuxonice/resume
 	local lv_img="$(cat /sys/power/tuxonice/image_exists | head -n 1)"
-	if [ ${lv_img} = 1 ]; then 
+	if [ ${lv_img} == 1 ]; then 
 		warn "There is no recognizable signature at location pointed by iresume|iswap"
 		warn "Do you want to proceed [NO|yes]? "
 		read local lv_asw
@@ -428,7 +432,7 @@ main() {
 		ishrl 2s
 		swp "swap" "${gv_swap}" "${gv_kswap}"
 	fi
-	[ -n "${gv_toi}" ] && ishrl 2r && do_resume
+	[ -n "${gv_toi}" ] && ishrl 2r && resume
 	rootfs
 	ishrl 4c
 	local IFS="${IFS}:"
@@ -444,7 +448,8 @@ _getopts() {
 	local dir
 	for arg in $(cat /proc/cmdline); do
     		case $arg in
-			rescue)     gv_shrl=1;;
+			rescue*)    gv_shrl=1;;
+			single)     gv_inrl=2;;
 			isqfsd=*)   dir=${arg#*=}
 				if [ "${dir%,*}" = "y" ]; then sqfsdir=${uv_sqfsdir:-/sqfsd}
 				else sqfsdir=${dir%,*}; fi
@@ -482,18 +487,19 @@ _init() {
 	for dir in dev proc sys newroot mnt/tok; do mkdir -p /$dir; done
 	mount -t proc proc /proc
 #	busybox --install -s
-	[ ${uv_check_env} ] || achk
-	[ ${uv_check_env} ] || bchk "cryptsetup" "--"
+	[ "${uv_check_env}" ] || achk
+	[ "${uv_check_env}" ] || bchk "cryptsetup" "--"
 	mount -t sysfs sysfs /sys
 	_getopts
 	[ -n "${gv_mod}" ] && { local IFS="${IFS},"
-		for module in ${gv_mod}; do modprobe ${module} &>/dev/null; done
+		for module in ${gv_mod}; do 
+			modprobe ${module} &> /dev/null
+		done
 	}
 	_modprobe boot
 	mount -t tmpfs tmpfs /dev
 	mdev -s
 	echo /sbin/mdev > /proc/sys/kernel/hotplug
-	[ -n "${gv_splash_theme}" ] && spalshd_init
 	main
 }
 _init
