init: update and refined the debug() function

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $Header: mkinitramfs-ll/init,v 0.6.0 2012/05/16 02:07:18 -tclover Exp $
+# $Header: mkinitramfs-ll/init,v 0.6.0 2012/05/16 15:56:47 -tclover Exp $
 #
 # WARNING: USE AT YOUR OWN RISK!
 # NEED SOME HELP? WHERE'S THE README FILE? YOU ASK? WHO KNOWS.
@@ -9,7 +9,7 @@ uv_init=/sbin/init      # init to execute after switching to real root
 uv_root_map=root        # self descriptive
 uv_check_env=0          # test if busybox/applets and the other binaries exist 
 uv_sqfsdir=/sqfsd       # squashed source dir related variable
-uv_sqfsd=usr:opt:bin:sbin:lib32	# squashed dirs variable
+uv_sqfsd=usr:bin:sbin:lib32:lib64 # squashed dirs variable
 # default values [edit at your own risk]
 gv_splashd=1
 gv_splash=verbose
@@ -20,15 +20,18 @@ warn() 	{ echo -ne "\033[1;33m * \033[0m$@\n"; }
 error() { echo -ne "\033[1;31m * \033[0m$@\n"; }
 
 debug() {
-	if $@; then echo "[$?]: $@" >> /init.log
-	else echo "[$?]: $@" >> /init.log; return 1; fi
+	${@#die }
+	local ret=$?
+	echo "[${ret}]: ${@#die }" >> /init.log
+	if [ "${1}" == "die" ] && [ ! "$?" ]; then die "[${ret}]: ${@#die }"
+	else return ${ret}; fi
 }
 
 die() {
 	umount -ln /mnt/tok
 	[ "${gv_splash}" == "silent" ] || verbose
 	error "$@"
-	info "Dropping you into a minimal shell..."
+	info "dropping you into a rescueshell..."
 	for lk in ${gv_lkey}; do dmclose "${lk}"; done
 	for ld in ${gv_ldev}; do losetup -d ${ld}; done
 	if [ -c "/dev/tty1" ]; then 
@@ -55,7 +58,7 @@ achk() {
 _rmmod() {
 	if [ -f "/etc/modules/${1}" ]; then
 		for mod in $(cat /etc/modules/${1}); do 
-			rmmod $(echo ${mod}|sed 's/-/_/g') &> /dev/null
+			debug rmmod ${mod}
 		done
 	fi
 }
@@ -63,12 +66,12 @@ _rmmod() {
 _modprobe() {
 	if [ -f "/etc/modules/${1}" ]; then
 		for mod in $(cat /etc/modules/${1}); do 
-			modprobe ${mod} &> /dev/null
+			debug modprobe ${mod}
 		done
 	fi
 }
 
-scmd() { [ $gv_splashd ] && echo "$@" >/lib/splash/cache/.splash; }
+scmd() { [ "${gv_splashd}" ] && echo "$@" >/lib/splash/cache/.splash; }
 verbose() { scmd "set mode verbose"; }
 silent() { scmd "set mode silent"; }
 smsg() { scmd "set message $@"; scmd "repaint"; }
@@ -86,15 +89,16 @@ spalshd_init() {
 splashd_stop() { [ "${gv_splashd}" ] && gv_splashd=1 scmd "exit"; }
 
 ishrl() {
-	debug info "init shell runlevel: ${1}"
+	info "init shell runlevel: ${1}"
+	local lv_scr="$(ls /etc/local.d/${1}?-*.sh &>/dev/null)"
+	if [ -n "${lv_scr}" ]; then
+		for scr in ${lv_scr}; do 
+			info "executing ${scr}..."
+			debug ${scr} || warn "${scr} failed"
+		done
+	fi
 	if [ "${gv_shrl}" == "${1}" ]; then verbose
-		local lv_scr="$(ls /etc/local.d/${1}?-*.sh &>/dev/null)"
-		if [ -n "${lv_scr}" ]; then
-			for scr in ${lv_scr}; do 
-				info "executing ${scr}..."
-				debug ${scr} || warn "${scr} failed"
-			done
-		fi
+		info "${1}: dropping into a rescueshell"
 		if [ -c "/dev/tty1" ]; then 
 			setsid sh -c "exec sh --login < /dev/tty1 > /dev/tty1 2>&1"
 		else sh --login; fi
@@ -106,11 +110,11 @@ _blkid() { echo $(blkid | grep "${1#*=}" | cut -d':' -f1); }
 getldkey() {
 	local lv_fname="${1##*/}"
 	if [ ! "${gv_crypt_loop}" ]; then
-		local lv_ldev="$(losetup -f)" || die "failed to create loop back devices"
-		losetup ${lv_ldev} ${1} || die "failed to setup losetup"
+		local lv_ldev="$(debug die losetup -f)"
+		debug die losetup ${lv_ldev} ${1}
 		gv_ldev="${lv_ldev}:${gv_ldev}"
 	fi
-	cryptsetup luksOpen "${lv_ldev}" "${lv_fname}" 
+	debug cryptsetup luksOpen "${lv_ldev}" "${lv_fname}" 
 	if [ "$?" ]; then
 		gv_kfile=/dev/mapper/"${lv_fname}"
 		gv_lkey="${lv_fname}:${gv_lkey}"
@@ -131,22 +135,21 @@ getkey() {
 	if [ "${lv_kmode}" != "pwd" ]; then
 		[ -n "${2}" ] || die "ik${4}=${1}:${2}:${3} device field empty."
 		[ -n "${3}" ] || die "ik${4}=${1}:${2}:${3} filepath field empty."
-		local lv_dev=$(_blkid "${2}"); gv_fpath="${3}"
+		local lv_dev=$(debug _blkid "${2}"); gv_fpath="${3}"
 		if [ -z "$(mount | grep /mnt/tok)" ]; then
 			if [ ! -b "${lv_dev}" ]; then
-				sleep 2; lv_dev=$(_blkid "${2}")
+				sleep 2; lv_dev=$(debug _blkid "${2}")
 				if [ ! -b "${lv_dev}" ]; then
 					info "Insert removable device and press Enter."
-					read; sleep 2; lv_dev=$(_blkid "${2}")
+					read; sleep 2; lv_dev=$(debug _blkid "${2}")
 				fi
 				while [ ! -b "${lv_dev}" ]; do
 					info "${lv_dev} does not exist, input a valid dev name"
 					info "e.g. '[/dev/]sdb1', 'LABEL=<label>' 'UUID=<uuid>'"
-					read lv_dev; sleep 2; lv_dev=$(_blkid "${lv_dev}")
+					read lv_dev; sleep 2; lv_dev=$(debug _blkid "${lv_dev}")
 				done
 			fi
-			mount -n -r "${lv_dev}" /mnt/tok &> /dev/null || \
-				die "Failed to mount ${lv_dev} remdev."
+			debug die mount -n -r "${lv_dev}" /mnt/tok
 			info "Removable device mounted."
 		fi
 		[ -f "/mnt/tok/${gv_fpath}" ] || \
@@ -164,12 +167,11 @@ getkey() {
 }
 
 dmclose() { 
-	[ -n "${2}" ] && vgchange -an ${2%-*} &>/dev/null
+	[ -n "${2}" ] && debug die vgchange -an ${2%-*}
 	local IFS="${IFS}:" 
 	for pv in ${1}; do 
 		warn "disabling ${pv%/*}..."
-		cryptsetup luksClose ${1%%-*} || cryptsetup remove ${1%%-*} || \
-		warn "${1%/*}: failed to close mapping."
+		debug cryptsetup luksClose ${1%%-*} || debug cryptsetup remove ${1%%-*}
 	done
 }
 
@@ -192,9 +194,8 @@ dmcrypt() {
 			[ -n "${lv_alp}" ] && lv_alp="--align-payload ${lv_alp}"
 		else lv_header=; lv_alp=; fi
 	fi
-	cryptsetup ${lv_arg} ${lv_dev} -c${lv_cph:-aes-xts-plain:sha256} \
-		-s${lv_ksz:-256} ${lv_ukf} ${lv_header} ${lv_alp} || \
-		die "failed to create ${lv_dev} cyphertext volume."
+	debug die cryptsetup ${lv_arg} ${lv_dev} -c${lv_cph:-aes-xts-plain:sha256} \
+		-s${lv_ksz:-256} ${lv_ukf} ${lv_header} ${lv_alp}
 }
 
 dmopen() { 
@@ -211,7 +212,7 @@ dmopen() {
 			lv_header="--header /mnt/tok/${lv_header}"
 		else die "${lv_header} detached header doesn't exist."; fi
 	fi
-	cryptsetup isLuks "${lv_dev}"
+	debug cryptsetup isLuks "${lv_dev}"
 	if [ ! "$?" ]; then
  		info "cre[ate] ${lv_dev} or dec[rypt] another LUKS PV? [cre|DEC]"
 		read local lv_asw 
@@ -219,44 +220,43 @@ dmopen() {
 			while true; do
 				info "Type in valid LUKS PV e.g. sda5|UUID=<uuid>|LABEL=<label>"
 				read lv_dev; lv_dev=$(_blkid "${lv_dev}")
-				cryptsetup isLuks "${lv_dev}" && break
+				debug cryptsetup isLuks "${lv_dev}" && break
 			done
-		elif [ "${lv_asw}" == "cre" ]; then dmcrypt; fi
+		elif [ "${lv_asw}" == "cre" ]; then debug dmcrypt; fi
 	fi
 	[ -b "${lv_dev}" ] || die "${lv_dev} block device doesn't exist."
-	cryptsetup isLuks "${lv_dev}" &>/dev/null || die "No valid LUKS PV found."
+	debug die cryptsetup isLuks "${lv_dev}"
 	lv_arg=luksOpen
 	if [ "${gv_cmode}" == "gpg" ]; then 
 		mv /dev/tty /dev/tty.bak; cp -a /dev/console /dev/tty
 		for i in 1 2 3; do
-			gpg -qd "${gv_kfile}" | cryptsetup "${lv_arg}" "${lv_dev}" "${lv_map}" \
+			debug gpg -qd "${gv_kfile}" | cryptsetup "${lv_arg}" "${lv_dev}" "${lv_map}" \
 				${lv_header} && break
 			[ ${i} -eq 3 ] && warn "...there's still a fallback..."
 		done
 		rm /dev/tty && mv /dev/tty.bak /dev/tty
 	elif [ "${gv_cmode}" == "ldk" ] || [ "${gv_cmode}" == "reg" ]; then 
-		cryptsetup "${lv_arg}" "${lv_dev}" "${lv_map}" -d "${gv_kfile}" \
+		debug cryptsetup "${lv_arg}" "${lv_dev}" "${lv_map}" -d "${gv_kfile}" \
 		${lv_header} || warn "...there's still a fallback..."
 	fi
 	if [ ! -b "/dev/mapper/${lv_map}" ]; then
-		cryptsetup "${lv_arg}" "${lv_dev}" "${lv_map}" ${lv_header} || \
-			die "Failed to decrypt ${lv_dev}."
+		debug die cryptsetup "${lv_arg}" "${lv_dev}" "${lv_map}" "${lv_header}"
 	fi
 }
 
 lvopen() {
 	[ "${uv_check_env}" ] || bchk "lvm" "--"
-	debug lvchange -ay ${1/-//}
-	if [ "$?" != "0" ] && [ -n "${2}" ]; then
+	if debug lvchange -ay ${1/-//}; then continue
+	elif [ -n "${2}" ]; then
 		local lv_pv="${2}" IFS="${IFS}:"
 		[ -e "/mnt/tok/${lv_pv}" ] && lv_pv="$(cat /mnt/tok/${lv_pv})"
 		for pv in ${lv_pv}; do debug dmopen "${pv}"; done
-		debug vgchange -ay ${1%-*} &> /dev/null || dmclose "${lv_pv}" "${1}"
+		debug vgchange -ay ${1%-*} || debug die dmclose "${lv_pv}" "${1}"
 	else die "${1} require a valid crypted physical volume"; fi
-	if [ -b "/dev/mapper/${1}" ]; then local lv_mapping=/dev/mapper/${1}
-	elif [ -b "/dev/${1/-//}" ]; then local lv_mapping=/dev/${1/-//}
+	if [ -b "/dev/mapper/${1}" ]; then local lvmap=/dev/mapper/${1}
+	elif [ -b "/dev/${1/-//}" ]; then local lvmap=/dev/${1/-//}
 	else die "${1} VG/LV do not exist."; fi
-	echo "$lv_mapping"
+	echo "${lvmap}"
 }
 
 mdopen() {
@@ -269,7 +269,7 @@ mdopen() {
 		else echo 'DEVICE /dev/sd??*' >> /etc/mdadm.conf; fi
 		echo ARRAY ${lv_dev} $(echo ${1} | cut -d'-' -f2) >> /etc/mdadm.conf
 	fi
-	mdadm --assemble --scan ${lv_dev} &>/dev/null || raidautorun
+	debug mdadm --assemble --scan ${lv_dev} || raidautorun
 	[ -b ${lv_dev} ] || die "failed to activate ${lv_dev} RAID array."
 }
 
@@ -283,20 +283,18 @@ squashd() {
 	for dir in $sqfsd; do
 		[ -e ."$sqfsdir/$dir".sfs ] || die "$dir.sfs image doesn't exist."
 		mkdir -p ."$sqfsdir/$dir"/rw && mkdir -p ."$sqfsdir/$dir"/ro
-		mount -t squashfs .${sqfsdir}/${dir}.sfs .${sqfsdir}/${dir}/ro \
-			-o nodev,loop,ro &>/dev/null || die "Failed to mount squashed ${dir} image."
-		mount -t aufs ${dir} ${dir} \
-			-o nodev,udba=reval,br:.${sqfsdir}/${dir}/rw:.${sqfsdir}/${dir}/ro \
-			&>/dev/null || die "Failed to mount squashed ${dir} aufs branch."
+		debug die mount -t squashfs .${sqfsdir}/${dir}.sfs \
+			.${sqfsdir}/${dir}/ro -o nodev,loop,ro
+		debug die mount -t aufs ${dir} ${dir} \
+			-o nodev,udba=reval,br:.${sqfsdir}/${dir}/rw:.${sqfsdir}/${dir}/ro
 	done
 }
 rootfs() {
 	local lv_kmod=${gv_kroot%%:*}
-	local lv_kdev="$(echo "$gv_kroot"|cut -d':' -f2)"
-	local lv_kfpt="$(echo "$gv_kroot"|cut -d':' -f3)"
+	local lv_kdev="$(echo "${gv_kroot}" | cut -d':' -f2)"
+	local lv_kfpt="$(echo "${gv_kroot}" | cut -d':' -f3)"
 	local lv_root=${gv_root%%:*}
-	local lv_fsck="$(echo "$gv_root"|cut -d':' -f2)"
-	local lv_rofs="$(echo "$gv_root"|cut -d':' -f3)"
+	local lv_rofs="$(echo "${gv_root}" | cut -d':' -f2)"
 :	local ${lv_lvm:=${gv_lvm%%,*}}
 :	${lv_lvm:=${gv_lvm_root}}
 :	local ${lv_raid:=${gv_raid%%,*}}
@@ -308,25 +306,23 @@ rootfs() {
 	ishrl 3d
 	[ -n "${lv_raid}" ] && mdopen "${lv_raid}"
 	if [ -n "${lv_lvm}" ]; then 
-		local lv_dev=$(debug lvopen "${lv_root}" "${lv_lvm}")
+		local lv_dev=$(debug die lvopen "${lv_root}" "${lv_lvm}")
 	elif [ -n "${gv_cmode}" ]; then info "...encrypted rootfs."
-		dmopen "${uv_root_map:-root}-${gv_root}" 
+		debug die dmopen "${uv_root_map:-root}-${gv_root}" 
 		local lv_dev=/dev/mapper/${uv_root_map:-root}
-	else local lv_dev=$(_blkid "${lv_root}"); fi
+	else local lv_dev=$(debug die _blkid "${lv_root}"); fi
 	ishrl 3f
-	[ -n "${lv_fsck}" ] && fsck ${lv_rofs} ${lv_dev} 
-	[ "$?" ] || { [ "${lv_fscf:-${uv_fscf:-y}}" = "y" ] && \
-		die "Failed to fsck rootfs, exit-code: $?"; }
+	[ -n "${lv_fsck}" ] && debug die fsck ${lv_rofs} ${lv_dev} 
 	ishrl 3m
-	mount ${lv_mtopt} ${lv_rofs} ${lv_dev} /newroot
+	debug mount ${lv_mtopt} ${lv_rofs} ${lv_dev} /newroot
 	if [ ! "$?" ]; then
 		if [ -n "${gv_cmode}" ]; then
-			dmclose "${lv_lvm:-${uv_root_map:-root}}" "${lv_lvm:+${lv_root}}"
+			debug die dmclose "${lv_lvm:-${uv_root_map:-root}}" "${lv_lvm:+${lv_root}}"
 		fi
 		die "Failed to mount rootfs."
 	fi
 	ishrl 3s
-	[ -n "${sqfsd}" ] && squashd
+	[ -n "${sqfsd}" ] && debug squashd
 	lv_lvm=; lv_mtopt=; gv_cmode=
 }
 
@@ -341,29 +337,30 @@ swp() {
 	[ -n "$lv_hdev" ] || die "${lv_mapp} dev|VG-LV is missing."
 	[ -n "$lv_type" ] || die "${lv_mapp} type file|swap is missing."
 	[ -n "$lv_sign" ] && lv_sign=:$lv_sign
-	getkey "${lv_kmod}" "${lv_kdev}" "${lv_kfpt}" "root"
+	debug getkey "${lv_kmod}" "${lv_kdev}" "${lv_kfpt}" "root"
 	[ -n "${lv_raid}" ] && mdopen "${lv_raid}"
 	if [ -n "${lv_lvm}" ]; then 
-		gv_dev=${lv_type}:$(lvopen "${lv_hdev}" "${lv_lvm}")${lv_sign}
+		gv_dev=${lv_type}:$(debug die lvopen "${lv_hdev}" "${lv_lvm}")${lv_sign}
 	elif [ -n "${gv_cmode}" ]; then info "...encrypted ${lv_mapp}."
-		dmopen "${lv_mapp}-${lv_hdev}"
+		debug die dmopen "${lv_mapp}-${lv_hdev}"
 		gv_dev=${lv_type}:/dev/mapper/${lv_mapp}${lv_sign}
 	else info "...unencrypted ${lv_mapp}."
-		gv_dev=${lv_type}:$(_blkid "${lv_hdev}")${lv_sign}
+		gv_dev=${lv_type}:$(ebug die _blkid "${lv_hdev}")${lv_sign}
 	fi
 	lv_lvm=; lv_raid=; gv_cmode=
 }
 
 resume() {
 	[ "${gv_splash}" == "silent" ] || smsg "Resuming..."
-	splashd_stop
-	[ -n "$(echo "${gv_toi}"|cut -d':' -s -f2)" ] && {
+	debug splashd_stop
+	if [ -n "$(echo "${gv_toi}" | cut -d':' -s -f2)" ]; then
 :		local ${lv_raid:=$(echo "${gv_raid}" | cut -d',' -f3)}
 :		local ${lv_lvm:=$(echo "${gv_lvm}" | cut -d',' -f3)}
 :		${lv_lvm:=${gv_lvm_resume}}
-		swp "resume"  "${gv_toi}" "${gv_kresume}"; }
-	_modprobe tuxonice
-	echo ${gv_dev} > /sys/power/tuxonice/resume
+		debug swp "resume"  "${gv_toi}" "${gv_kresume}"
+	fi
+	debug _modprobe tuxonice
+	debug die echo ${gv_dev} > /sys/power/tuxonice/resume
 	local lv_img="$(cat /sys/power/tuxonice/image_exists | head -n 1)"
 	if [ ${lv_img} == 1 ]; then 
 		warn "There is no recognizable signature at location pointed by iresume|iswap"
@@ -378,12 +375,12 @@ resume() {
 		/sys/power/tuxonice/user_interface/program
 	[ -z "$(cat /sys/power/tuxonice/user_interface/program)" ] && \
 		echo $(which tuxoniceui_fbsplash) >/sys/power/tuxonice/user_interface/program
-	mount -n -o remount,ro / &>/dev/null
+	debug die mount -n -o remount,ro
 	info "RESUMING from hibernation S[4-5]."
-	echo > /sys/power/tuxonice/do_resume
-	mount -n -o remount,rw / &>/dev/null
-	echo > /sys/power/tuxonice/image_exists
-	_rmmod tuxonice
+	debug die echo > /sys/power/tuxonice/do_resume
+	debug die mount -n -o remount,rw /
+	debug die echo > /sys/power/tuxonice/image_exists
+	debug _rmmod tuxonice
 	die "Resume from hibernation failed, image destroied."
 }
 
@@ -391,14 +388,14 @@ switch() {
 	echo > /proc/sys/kernel/hotplug
 	[ "${gv_splash}" == "silent" ] && silent && smsg "Switching / ..."
 	info "SWITCHING root '/'..."
-	splashd_stop
+	debug splashd_stop
 	sleep 1
 	ishrl 4u
-	umount -l /proc
-	umount -l /sys
-	umount -l /dev
+	debug die umount -l /proc
+	debug die umount -l /sys
+	debug die umount -l /dev
 	ishrl 4s
-	exec switch_root /newroot ${uv_init:-/sbin/init} ${gv_inrl}
+	debug die exec switch_root /newroot ${uv_init:-/sbin/init} ${gv_inrl}
 }
 
 imsg() { [ -e /etc/msg ] && info "$(cat /etc/msg)"; }
@@ -408,23 +405,21 @@ main() {
 	if [ -n "${gv_kmap}" ]; then
 		for dir in /usr/share/keymaps /etc /; do
 			if [ -f "${dir}/${gv_kmap}" ]; then
-				loadkmap < "${dir}/${gv_kmap}" && break \
-					|| error "Failed to load ${gv_kmap} keymap"
+				debug die loadkmap < "${dir}/${gv_kmap}" && break
 			fi
 		done
 	fi
 	if [ -n "${gv_font}" ]; then
 		for dir in /usr/share/consolefonts /etc /; do
 			if [ -f "${dir}/${gv_font}" ]; then
-				loadfont < "${dir}/${gv_font}" && break \
-					|| error "Failed to load ${gv_font} font"
+				debug die loadfont < "${dir}/${gv_font}" && break
 			fi
 		done
 	fi
-	imsg
+	debug imsg
 	ishrl 1
-	_modprobe gpg
-	_modprobe remdev
+	debug _modprobe gpg
+	debug _modprobe remdev
 	if [ -n "${gv_swap}" ]; then
 :		local ${lv_raid:=$(echo "${gv_raid}" | cut -d',' -f2)}
 :		local ${lv_lvm:=$(echo "${gv_lvm}" | cut -d',' -f2)}
@@ -433,15 +428,15 @@ main() {
 		swp "swap" "${gv_swap}" "${gv_kswap}"
 	fi
 	[ -n "${gv_toi}" ] && ishrl 2r && resume
-	rootfs
+	debug rootfs
 	ishrl 4c
 	local IFS="${IFS}:"
 	for lk in ${gv_lkey}; do dmclose "${lk}"; done
 	for ld in ${gv_ldev}; do losetup -d ${ld}; done
-	_rmmod gpg
-	umount -n -l /mnt/tok
-	_rmmod remdev
-	switch
+	debug _rmmod gpg
+	debug die umount -n -l /mnt/tok
+	ebug _rmmod remdev
+	debug switch
 }
 
 _getopts() {
@@ -485,23 +480,23 @@ _init() {
 #	dmesg -n 1
 	umask 0077
 	for dir in dev proc sys newroot mnt/tok; do mkdir -p /$dir; done
-	mount -t proc proc /proc
+	debug die mount -t proc proc /proc
 #	busybox --install -s
 	[ "${uv_check_env}" ] || achk
 	[ "${uv_check_env}" ] || bchk "cryptsetup" "--"
-	mount -t sysfs sysfs /sys
-	_getopts
-	[ -n "${gv_mod}" ] && { local IFS="${IFS},"
+	debug die mount -t sysfs sysfs /sys
+	debug _getopts
+	debug _modprobe boot
+	debug die mount -t tmpfs tmpfs /dev
+	debug die mdev -s
+	debug die echo /sbin/mdev > /proc/sys/kernel/hotplug
+	if [ -n "${gv_mod}" ]; then local IFS="${IFS},"
 		for module in ${gv_mod}; do 
-			modprobe ${module} &> /dev/null
+			debug modprobe ${module}
 		done
-	}
-	_modprobe boot
-	mount -t tmpfs tmpfs /dev
-	mdev -s
-	echo /sbin/mdev > /proc/sys/kernel/hotplug
-	main
+	fi
+	debug main
 }
-_init
+debug _init
 
 # vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
