init: minor update; well, ldk keyfile mode fails for no reason: cannot fix it

diff --git a/init b/init
--- a/init
+++ b/init
@@ -77,17 +77,13 @@ shell_runlevel() {
 		exec /bin/sh; fi
 }
 
-losetup_associate() {
-	lv_ldk_dev="$(losetup -f)" || die "Create or append max_loop=<int> to the cmdline."
-	losetup ${lv_ldk_dev} ${1} || die "Failed to setup losetup."
-	echo ${lv_ldk_dev}
-}
-
 find_blkd() { echo $(blkid | grep "${1#*=}" | cut -d':' -f1); }
 
 ldkey() {
 	[ $gv_crypt_loop ] && local lv_ldk_dev="${1}" || {
-		local lv_ldk_dev=$(losetup_associate "${1}")
+		local lv_ldk_dev
+		lv_ldk_dev="$(losetup -f)" || die "Create or append max_loop=<int> to the cmdline."
+		losetup ${lv_ldk_dev} ${1} || die "Failed to setup losetup."
 		gv_ldk_dev="${gv_ldk_dev}:${lv_ldk_dev}"
 	}
 	cryptsetup luksOpen "${lv_ldk_dev}" "${2}" && gv_kfile=/dev/mapper/"${2}" \
