mkifs-ll_bb: v0.4.1 version bump with full GNU style switches

diff --git a/mkifs-ll_bb b/mkifs-ll_bb
--- a/mkifs-ll_bb
+++ b/mkifs-ll_bb
@@ -1,50 +1,54 @@
 #!/bin/bash
-# $Id: mkinitramfs-ll/mkifs-ll_bb[.bash],v 0.4.0 2011/11/21 -tclover Exp $
+# $Id: mkinitramfs-ll/mkifs-ll_bb[.bash],v 0.4.1 2011/12/05 -tclover Exp $
 
 usage() {
   cat << EOF
   usage:
-  ${0##*/} [-b|--build [-m|--minimal] [--uCl-arch=i386] ] [--kmap=map:kmap]
-  -b, --build	          build a [minimal|full applets featured] static busybox binary 
-  -m, --minimal	          build busybox with minimal applets, default is full applets
-  -i, --install	          install busybox with symliks to \$BINDIR, require -b|--build
-      --keymap=map:kmap   generate kmap keymap using map as input keymap.
-      --uCl-arch=i386     ARCH string needed to build busybox linked uClibc instead of..		
-  -u, --usage             print the usage/help and exit
+  ${0##*/} [-b|--build [-m|--minimal] [-Y[|--kmap=]map:kmap] [OPTIONS]
+  -D|--build               build a [minimal|full applets featured] static busybox binary 
+  -i|--install             install busybox with symliks to \$opts[-bindir], require -b
+  -n|--minimal             build busybox with minimal applets, default is full applets
+  -U|--ucl-arch i386       ARCH string needed to build busybox against uClibc	
+  -Y|--key-map <map:kmap>  generate kmap keymap using map as input keymap
+  -B|--bindir bin          copy builded binary to <bin> directory
+  -u|--usage               print the usage/help and exit
 EOF
 }
 
 [[ $# = 0 ]] && usage && exit 0
-
+opt=$(getopt --long build,install,key-map:,minimal,ucl-arch,usage,bindir: \
+	  -o inuDU:B:Y: -n ${0##*/} -- "$@" || usage && exit 0)
+eval set -- "$opt"
+[[ -z "${opts[*]}" ]] && declare -A opts
 while [[ $# > 0 ]]; do
 	case $1 in
-		-b|--build) CONFIG=y; BBB=y; shift;;
-		-m|--minimal) CONFIG=m; shift;;
-		-i|--install) IBB=y; shift;;
-		--tmp=*) TMP_DIR=${1#*=}; shift;;
-		--ucl-arch=*) UCL_ARCH=${1#*=}-uClibc-; shift;;
-		--keymap=*) KBB=y; KEYMAP_IN=$(echo ${1#*=}|cut -d':' -f1)
-			KEYMAP_OUT=$(echo ${1#*=}|cut -d':' -f2); shift;;
-		-u|--usage|*) usage; exit 0;;
+		-u|--usage) usage; exit 0;;
+		-D|--build) opts[build]=y; shift 2;;
+		-i|--intsall) opts[install]=y; shift 2;;
+		-n|--minimal) opts[minimal]=y; shift 2;;
+		-B|--bindir) opts[bindir]="${2}"; shift 2;;
+		-U|--ucl-arch) opts[ucl-arch]=${2}; shift 2;;
+		-Y|--key-map) opts[key-map]="${2}"; shift 2;;
+		--) shift; break;;
 	esac
 done
 
+[[ -n "${opts[workdir]}" ]] || opts[workdir]="$(pwd)"
+[[ -n "${opts[bindir]}" ]] || opts[bindir]="${opts[workdir]}"/bin
 [[ -f ./mkifs-ll.conf ]] && source ./mkifs-ll.conf
-:	${WORKDIR:=$(pwd)}
-:	${MISCDIR:=$WORKDIR/misc}
-:	${BINDIR:=$WORKDIR/bin}
+mkdir -p "${opts[bindir]}"
 
 error() { echo -ne "\e[1;31m* \e[0m$@\n"; }
 die()   { error "$@"; exit 1; }
 
 build_busybox() {
 	cd "${PORTDIR:-/usr/portage}"/sys-apps/busybox || die "eek"
-	BBT=$(emerge -pvO busybox|grep -o "busybox-[-0-9.r]*")
+	BBT=$(emerge -pvO busybox | grep -o "busybox-[-0-9.r]*")
 	ebuild $BBT.ebuild clean || die "clean failed"
 	ebuild $BBT.ebuild unpack || die "unpack failed"
 	cd "${PORTAGE_TMPDIR:-/var/tmp}"/portage/sys-apps/$BBT/work/$BBT || die "eek!"
 
-	if [[ "$CONFIG" = "m" ]]; then
+	if [[ -n "${opts[minimal]}" ]]; then
 		make allnoconfig || die "eek!"
 		sed -e "s|# CONFIG_INSTALL_NO_USR is not set|CONFIG_INSTALL_NO_USR=y|" \
 		-e "s|# CONFIG_STATIC is not set|CONFIG_STATIC=y|" \
@@ -94,56 +98,46 @@ build_busybox() {
 		-i .config || die "cfg failed"; fi
 
 	# For uClibc users, you need to adjust the cross compiler prefix properly (i386-uclibc-)
-	if [[ -n "$UCL_ARCH" ]]; then
-	sed -e "s|CONFIG_CROSS_COMPILER_PREFIX=\"\"|CONFIG_CROSS_COMPILER_PREFIX=\"$UCL_ARCH\"|" \
-		-i .config || die "setting uClib ARCH failed"; fi
+	if [[ -n "${opts[ucl-arch]}" ]]; then
+	sed -e "s|CONFIG_CROSS_COMPILER_PREFIX=\"\"|CONFIG_CROSS_COMPILER_PREFIX=\"${opts[ucl-arch]}\"|" \
+		-i .config || die "setting uClib ARCH failed"
+	fi
 	make && make busybox.links || die "bb build failed"
 }
 
 install_busybox() {
-	[[ -e "$TMP_DIR" ]] && {
-		make install CONFIG_PREFIX="$TMP_DIR"/busybox
-		rm -rf /tmp/busybox; }
-	./applets/install.sh "$BINDIR" --symlinks
+	[[ -e "${opts[tmpdir]}" ]] && {
+		make install CONFIG_PREFIX="${opts[tmpdir]}"/busybox
+		rm -rf "${opts[tmpdir]}"/busybox
+	}
+	./applets/install.sh "${opts[bindir]}" --symlinks
 }
 
 build_keymap() { 
-	# save the current keymap
+	local KEYMAP_IN=$(echo "${opts[key-map]}" | cut -d':' -f1)
+	local KEYMAP_OUT=$(echo "${opts[key-map]}" | cut -d':' -f2)
 	dumpkeys > default_keymap || die "dumping keymap failed"
 	loadkeys $KEYMAP_IN || die "loading $KEMAP_IN failed"
-	[[ "$UNICODE" = "y" ]] && { 
-		dumpkeys|loadkeys -u || die "unicode conversion failed"
-	}
+	dumpkeys|loadkeys -u || die "unicode conversion failed"
 	./busybox dumpkmap > $KEYMAP_OUT || die "keymap build failed"
-	# load back your keymap
 	loadkeys default_keymap && rm default_keymap || die "re-loading default keymap failed"
+	echo "${KEYMAP_OUT}"
 }
 
-[[ "${BBB}" = "y" ]] && {
-	mkdir -p "$BINDIR"
+[[ -n "${opts[build]}" ]] && {
 	build_busybox
-	[[ "$IBB" = "y" ]] && install_busybox
-	cp -a busybox "$BINDIR"/ || die "failed to copy bb binary"
-	cp busybox.links "$BINDIR"/applets || die "failed to copy applets"
-	unset CONFIG IBB
-}
-
-[[ "${KBB}" = "y" ]] && {
-	mkdir -p "$BINDIR"
-	[[ "$BBB" != "y" ]] && cd "$BINDIR" || die "eek!"
-	build_keymap
-	[[ "$BBB" = "y" ]] && { 
-		cp $KEYMAP_OUT "$BINDIR"/ || die "$KEYMAP_OUT copy failed"
-	}
-	KEYMAPS+=":$KEYMAP_OUT"
-	unset KEYMAP_IN KEYMAP_OUT UNICODE KBB
-}
-
-[[ "${BBB}" = "y" ]] && {
+	[[ -n "${opts[install]}" ]] && install_busybox
+	cp -a busybox "${opts[bindir]}"/ || die "failed to copy bb binary"
+	cp busybox.links "${opts[bindir]}"/applets || die "failed to copy applets"
 	cd "${PORTDIR:-/usr/portage}"/sys-apps/busybox || die "eek"
 	ebuild $BBT.ebuild clean || die "eek"
-	cd "$WORKDIR" || die "eek!"
-	unset BBB BBT
+	cd "${opts[workdir]}" || die "eek!"
 }
+
+[[ -n "${opts[key-map]}" ]] && { cd "${opts[bindir]}" || die "eek!"
+	opts[keymap]+=:$(build_keymap)
+}
+
+unset BBT
 
 # vim:fenc=utf-8:ci:pi:sts=0:sw=4:ts=4:
