mkifs-ll_bb keymap gen fix and quoting update when copying stuff... maybe more careful quoting will come later

diff --git a/mkifs-ll_bb b/mkifs-ll_bb
--- a/mkifs-ll_bb
+++ b/mkifs-ll_bb
@@ -98,7 +98,7 @@ install_busybox() {
 	if [ -e "$TMP_DIR" ]; then
 		make install CONFIG_PREFIX="$TMP_DIR"/busybox
 		rm -rf /tmp/busybox; fi
-	./applets/install.sh $BIN/ --symlinks
+	./applets/install.sh "$BIN" --symlinks
 }
 
 build_keymap() { 
@@ -110,31 +110,26 @@ build_keymap() {
 	./busybox dumpkmap > $KEYMAP_OUT || die "keymap build failed"
 	# load back your keymap
 	loadkeys default_keymap && rm default_keymap || die "re-loading default keymap failed"
-	if [ "$(pwd)" != "$WORKDIR"/bin ]; then 
-		cp $KEYMAP_OUT $BIN/ || die "$KEYMAP_OUT copy failed"; fi
-	unset KEYMAP_IN
-	unset KEYMAP_OUT
-	unset UNICODE
 }
 
 if [ "${BBB}" = "y" ]; then
-	mkdir -p $BIN
+	mkdir -p "$BIN"
 	build_busybox
 	[ "$IBB" = "y" ] && install_busybox
-	cp -a busybox $BIN/ || die "failed to copy bb binary"
-	cp busybox.links $BIN/applets || die "failed to copy applets"
-	unset CONFIG
-	unset IBB; fi
+	cp -a busybox "$BIN"/ || die "failed to copy bb binary"
+	cp busybox.links "$BIN"/applets || die "failed to copy applets"
+	unset CONFIG IBB; fi
 
 if [ "${KBB}" = "y" ]; then
-	mkdir -p $BIN
-	[ "${BBB}" != "y" ] && cd $BIN || die "eek!"
+	mkdir -p "$BIN"
+	[ "$BBB" != "y" ] && cd "$BIN" || die "eek!"
 	build_keymap
-	unset KBB; fi
+	if [ "$BBB" = "y" ]; then 
+		cp $KEYMAP_OUT "$BIN"/ || die "$KEYMAP_OUT copy failed"; fi
+	unset KEYMAP_IN KEYMAP_OUT UNICODE KBB; fi
 
 if [ "${BBB}" = "y" ]; then
 	cd ${PORTDIR:-/usr/portage}/sys-apps/busybox || die "eek"
 	ebuild $BBT.ebuild clean || die "eek"
 	cd $WORKDIR || die "eek!"
-	unset BBB
-	unset BBT; fi
+	unset BBB BBT; fi
