mkifs-ll{,_gen,_bb,_gpg} update following previous commit

diff --git a/mkifs-ll_bb b/mkifs-ll_bb
--- a/mkifs-ll_bb
+++ b/mkifs-ll_bb
@@ -1,8 +1,8 @@
 #!/bin/bash
-revision=0.3.2_p20110906
+revision=0.3.3_p20111020
 
 usage() {
-	cat << EOF
+  cat << EOF
   usage:
   ${0##*/} [-b|--build [-m|--minimal] [--uCl-arch=i386] ] [--kmap=map:kmap]
   -b, --build		build a static busybox.
@@ -15,7 +15,7 @@ usage() {
 EOF
 }
 
-if [[ $# = 0 ]]; then usage; exit 0; fi
+[[ $# = 0 ]] && usage && exit 0
 
 while [[ $# > 0 ]]; do
 	case $1 in
@@ -31,17 +31,13 @@ while [[ $# > 0 ]]; do
 	esac
 done
 
-[ -f ./mkifs-ll.conf ] && . ./mkifs-ll.conf
+[[ -f ./mkifs-ll.conf ]] && source ./mkifs-ll.conf
 :	${WORKDIR:=$(pwd)}
 :	${MISC:=$WORKDIR/misc}
 :	${BIN:=$WORKDIR/bin}
 
 error() { echo -ne "\033[1;31m* \033[0m$@\n"; }
-
-die() {
-	error "$@"
-	exit 1
-}
+die()   { error "$@"; exit 1; }
 
 build_busybox() {
 	cd ${PORTDIR:-/usr/portage}/sys-apps/busybox || die "eek"
@@ -50,7 +46,7 @@ build_busybox() {
 	ebuild $BBT.ebuild unpack || die "unpack failed"
 	cd ${PORTAGE_TMPDIR:-/var/tmp}/portage/sys-apps/$BBT/work/$BBT || die "eek!"
 
-	if [ "$CONFIG" = "m" ]; then
+	if [[ "$CONFIG" = "m" ]]; then
 		make allnoconfig || die "eek!"
 		sed -e "s|# CONFIG_INSTALL_NO_USR is not set|CONFIG_INSTALL_NO_USR=y|" \
 		-e "s|# CONFIG_STATIC is not set|CONFIG_STATIC=y|" \
@@ -88,16 +84,16 @@ build_busybox() {
 		-i .config || die "cfg failed"; fi
 
 	# For uClibc users, you need to adjust the cross compiler prefix properly (i386-uclibc-)
-	if [ -n "$UCL_ARCH" ]; then
+	if [[ -n "$UCL_ARCH" ]]; then
 	sed -e "s|CONFIG_CROSS_COMPILER_PREFIX=\"\"|CONFIG_CROSS_COMPILER_PREFIX=\"$UCL_ARCH\"|" \
 		-i .config || die "setting uClib ARCH failed"; fi
 	make && make busybox.links || die "bb build failed"
 }
 
 install_busybox() {
-	if [ -e "$TMP_DIR" ]; then
+	[[ -e "$TMP_DIR" ]] && {
 		make install CONFIG_PREFIX="$TMP_DIR"/busybox
-		rm -rf /tmp/busybox; fi
+		rm -rf /tmp/busybox; }
 	./applets/install.sh "$BIN" --symlinks
 }
 
@@ -105,31 +101,32 @@ build_keymap() {
 	# save the current keymap
 	dumpkeys > default_keymap || die "dumping keymap failed"
 	loadkeys $KEYMAP_IN || die "loading $KEMAP_IN failed"
-	if [ "$UNICODE" = "y" ]; then 
-		dumpkeys|loadkeys -u || die "unicode conversion failed"; fi
+	[[ "$UNICODE" = "y" ]] && { 
+		dumpkeys|loadkeys -u || die "unicode conversion failed"; }
 	./busybox dumpkmap > $KEYMAP_OUT || die "keymap build failed"
 	# load back your keymap
 	loadkeys default_keymap && rm default_keymap || die "re-loading default keymap failed"
 }
 
-if [ "${BBB}" = "y" ]; then
+[[ "${BBB}" = "y" ]] && {
 	mkdir -p "$BIN"
 	build_busybox
-	[ "$IBB" = "y" ] && install_busybox
+	[[ "$IBB" = "y" ]] && install_busybox
 	cp -a busybox "$BIN"/ || die "failed to copy bb binary"
 	cp busybox.links "$BIN"/applets || die "failed to copy applets"
-	unset CONFIG IBB; fi
+	unset CONFIG IBB; }
 
-if [ "${KBB}" = "y" ]; then
+[[ "${KBB}" = "y" ]] && {
 	mkdir -p "$BIN"
-	[ "$BBB" != "y" ] && cd "$BIN" || die "eek!"
+	[[ "$BBB" != "y" ]] && cd "$BIN" || die "eek!"
 	build_keymap
-	if [ "$BBB" = "y" ]; then 
-		cp $KEYMAP_OUT "$BIN"/ || die "$KEYMAP_OUT copy failed"; fi
-	unset KEYMAP_IN KEYMAP_OUT UNICODE KBB; fi
+	[[ "$BBB" = "y" ]] && { 
+		cp $KEYMAP_OUT "$BIN"/ || die "$KEYMAP_OUT copy failed"; }
+	export KEYMAPS+=",$KEYMAP_OUT"
+	unset KEYMAP_IN KEYMAP_OUT UNICODE KBB; }
 
-if [ "${BBB}" = "y" ]; then
+[[ "${BBB}" = "y" ]] && {
 	cd ${PORTDIR:-/usr/portage}/sys-apps/busybox || die "eek"
 	ebuild $BBT.ebuild clean || die "eek"
 	cd $WORKDIR || die "eek!"
-	unset BBB BBT; fi
+	unset BBB BBT; }
