mkifs-ll: v0.4.0 version bump with cryptsetup-1.4.1 and kernel 3.1 support

diff --git a/mkifs-ll b/mkifs-ll
--- a/mkifs-ll
+++ b/mkifs-ll
@@ -1,6 +1,6 @@
 #!/bin/bash
-# $Id: mkinitramfs-ll/mkifs-ll[.bash],v 0.3.6 2011/11/01 -tclover Exp $
-revision=0.3.6_p20111101
+# $Id: mkinitramfs-ll/mkifs-ll[.bash],v 0.4.0 2011/11/25 -tclover Exp $
+revision=0.4.0
 
 usage() {
   cat <<-EOF
@@ -97,11 +97,18 @@ rm -rf "$INITDIR" || die "eek!"
 mkdir -p "$INITDIR" && cd "$INITDIR" || die "eek!"
 mkdir -p {,s}bin dev proc root sys usr/{bin,sbin} newroot || die "eek!"
 [[ -n "$(uname -a|grep x86_64)" ]] && ARCH=64 || ARCH=32
-mkdir -p lib$ARCH/splash/cache etc/{modules,splash} mnt/tok || die "eek!"
+mkdir -p lib$ARCH/splash/cache etc/{modules,splash,local.d} mnt/tok || die "eek!"
 ln -sf lib$ARCH lib || die "eek!" && unset ARCH
 
 cp -a /dev/{console,random,urandom,mem,null,tty,tty1,zero} dev/ || addnodes
+[[ $(echo ${K_VERSION} | cur -d'.' -f1 ) = 3 ]] && \
+	[[ $(echo ${K_VERSION} | cut -d'.' -f2) >= 1 ]] && { 
+	cp -a {/,}dev/loop-control || mknod dev/loop-control c 10 237 || die "eek!"
+}
 cp -a "$WORKDIR"/init . && chmod 775 init || die "failed to copy init"
+cp -a {/,}lib/modules/$K_VERSION/modules.dep || die "failed to copy modules.dep"
+[[ -e $MISCDIR/msg ]] && cp $MISCDIR/msg etc/
+for scr in $(ls $MISCDIR/*.sh); do cp $scr etc/local.d/; done
 
 if [[ -x "$BINDIR"/busybox ]]; then BINARIES+=:bin/busybox
 elif [[ "$(which bb)" != "bb not found" ]]; then 
@@ -116,7 +123,9 @@ if [[ -e "$BINDIR"/applets ]]; then
 			*) ln -s bin/busybox .$app || die "eek!";;
 		esac
 	done
-else sed -e 's|#\t/bin/busybox|\t/bin/busybox|' -i init || die "eek!"; fi
+else sed -e 's|#\t/bin/busybox|\t/bin/busybox|' -i init || die "eek!"
+	ln -sf bin/busybox linuxrc || die "eek!"
+	cd bin && ln -sf busybox sh && cd .. || die "eek!"; fi
 
 [[ -n "$iAUFS" ]] && { BINARIES+=:umount.aufs:mount.aufs
 	for fs in {au,squash}fs
