mkifs-ll* update/refresh: removed unecessary FS variable, now module name should be set to MOD only. and yes, cmdline args will override default values.

diff --git a/mkifs-ll b/mkifs-ll
--- a/mkifs-ll
+++ b/mkifs-ll
@@ -1,34 +1,25 @@
 #!/bin/bash
-revision=0.3.2_p20110830
+revision=0.3.3_p20110906
 
-error() { echo -ne "\033[1;31m* \033[0m$@\n"; }
-
-die() {
-	error "$@"
-	exit 1
-}
-
-short_help() {
+usage() {
 	cat << EOF
    ${0##*/} [OPTIONS]
-      --aufs		adds aufs[2] support to the initramfs for sqfsd (aufs2+squashfs).
-  -e, --e-version=str 	optional, append str extra version after k-version to the initramfs.
-  -k, --k-version=str	build an initramfs for 'k-version=\${KV:-\$(uname -r)}' kernel version.
-      --font=<font>	adds <font>, if \`=*' is omitted will add default font if available.
-  -f, --full		optional, build an initramfs with '--aufs --bin-dir --font --fs --lvm --gpg --misci --toi'.
-      --fs=<fs>		adds <fs> drivers to the initramfs, if empty will try to include 
-      			{btr,j,reiser,squash,x}fs,reiser4; it's a spaces ' ' separated list.
-      --fsck=<rootfs>	adds fsck.<rootfs> plus linked libraries to get fsck support for rootfs,
-      			if <rootfs> is the empty string will default to ext4.
+      --aufs		adds aufs[2] support to the initramfs for (aufs2+squashfs).
+  -e, --e-version=<str>	append <str> extra version after k-version to the initramfs.
+  -k, --k-version=<str>	build an initramfs for 'k-version=\${KV:-\$(uname -r)}' kernel version.
+      --font=<font>	adds <font> to the initramfs.
+  -f, --full		build with '--aufs --bin-dir --font --lvm --gpg --misci --toi' options.
+      --mod=<mod>	adds '<mod>' module, space separated list, to the initramfs.
+      --fsck=<fs>	adds fsck.<fs> binary with linked libraries for fsck.<fs> support.
       --bin-dir=bin 	use binaries [gpg/options.skel|busybox/applets|kmap-ARCH.bin] from 'bin'.
-      --comp-cmd=cmd	compression command to use to build initramfs, default is 'xz -9 --check=crc32'.
-  -g, --gpg 		adds GPG support, require a static app-crypt/gnupg-1.4.x build and options.skel.
-      --prefix=mvlinu.	prefix scheme to name the initramfs default is \`kernel-'.
+      --comp-cmd=cmd	compression command to use to build initramfs, default is xz.
+  -g, --gpg 		adds GPG support, require a static app-crypt/gnupg-1.4 and options.skel.
+      --prefix=mvlinuz.	prefix scheme to name the initramfs default is \`kernel-'.
       --kmap=km-x86.bin adds 'km-x86.bin' key-map in the initramfs, full path is required.
   -l, --lvm 		adds LVM2 support, require a static sys-fs/lvm2 build.
-      --misc-dir=misc use 'misc/{.gnupg/gpg.conf,share/gnupg/options.skel,initramfs-ll.conf}', optionaly 
-      			one can add manpages and info files of gpg/lvm in misc/share as the whole directory 
-			will be copied over into the initramfs, if the '=*' is omitted will default to './misc'.
+      --misc-dir=misc 	use 'misc/{.gnupg/gpg.conf,share/gnupg/options.skel,mkifs-ll.conf}',  
+      			one can add manpages and info files of gpg/lvm in misc/share as the whole 
+			directory will be copied over into the initramfs.
       --splash=theme	splash theme to include in the initramfs.
       --toi		adds tuxonice support.
   -h, --help		print this help.
@@ -37,44 +28,64 @@ short_help() {
   usages:
   # called without an argument, will build an initramfs for \$(uname -r) with LUKS support.
 
-  # building with full LUKS/GPG/LVM2/AUFS2 support for kernel 3.0.3-git with an extra 'd0' string version.
-  ${0##*/} -e d0 -k 3.0.3-git -f
+  # build with LUKS/GPG/LVM2/AUFS2 support for kernel 3.0.3-git with 'd0' string extra version.
+  ${0##*/} --e-version=d0 --k-version=3.0.3-git --full
   
   <str> 	string
-  <font>	full path to font.
-  <fs> 		file system e.g. xfs, reiser4.
+  <font>	full path to font, easy to include one into 'bin' directory and add its name
+  		into \${FONT:=\$BIN/<name>} definition into mkifs-ll.conf
+  <km-x86.bin>	same as above for KEYMMAP variable.
+  <fs> 		file system e.g. xfs, default is 'btrfs jfs reiserfs squashfs xfs reiser4'.
   <theme>	full path to splash 'theme'.
-  <rootfs> 	root file sytem.
-  bin		directory with the necessary binaries to build an initramfs.
-  misc		second local directory with extra necessary files.
-  --*-dir	bin-dirand misc-dir argument can be used without =* and will default to using ./bin and ./misc.
-  --*=		all arguments will default to default value definied in \$MISC/initramfs-ll.conf if empty.
+  <fs> 		file sytem.
+  bin		full path to directory with the necessary binaries to build an initramfs.
+  misc		second full path to directory with extra necessary files.
+  --*=		all arguments will use default value definied in mkifs-ll.conf if empty.
 EOF
 }
 
+error() { echo -ne "\033[1;31m* \033[0m$@\n"; }
+info() 	{ echo -ne "\033[1;32m* \033[0m$@\n"; }
+
+die() {
+	error "$@"
+	exit 1
+}
+
+addmodule() {
+	for mod in $@; do
+		local module=$(find /lib/modules/$K_VERSION -name $mod.ko)
+		if [ -z $module ]; then info "$mod does not exist"
+		else 	mkdir -p .${module%/*}
+			cp -ar $module .${module%/*} || die "$module copy failed"
+		fi
+	done
+}
+
+[ $# = 0 ] && info "initramfs will be build with only LUKS support."
+
 while [[ $# > 0 ]]; do
 	case $1 in
-		-h|--help) short_help; exit 0;;
 		-v|--version) echo "version $revision"; exit 0;;
 		--aufs) iAUFS=y; shift;;
-		--bin-dir*) [ -n "${1#*=}" ] && BIN=${1#*=}; shift;;
-		--comp-cmd*) [ -n "${1#*=}" ] && CMD=${1#*=}; shift;;
+		--bin-dir=*) [ -n "${1#*=}" ] && BIN=${1#*=}; shift;;
+		--comp-cmd=*) [ -n "${1#*=}" ] && CMD=${1#*=}; shift;;
 		-e) E_VERSION=$2; shift 2;;
 		--e-version=*) [ -n "${1#*=}" ] && E_VERSION=${1#*=}; shift;;
-		--font*) [ -n "${1#*=}" ] && FONT=${1#*=}; shift;;
+		--font=*) [ -n "${1#*=}" ] && FONT=${1#*=}; shift;;
 		-f|--full) iAUFS=y; iGPG=y; iLVM=y, iTOI=y; shift;;
-		--fs*)	[ -n "${1#*=}" ] && FS=kernel/fs/${1#*=}; shift;;
-		--fsck*) [ -n "${1#*=}" ] && FSCK=${1#*=}; shift;;
+		--mod=*) [ -n "${1#*=}" ] && MOD=${1#*=}; shift;;
+		--fsck=*) [ -n "${1#*=}" ] && FSCK=${1#*=}; shift;;
 		-g|--gpg) iGPG=y; shift;;
-		--prefix*) PREFIX=${1#*=}; shift;; 
+		--prefix=*) PREFIX=${1#*=}; shift;; 
 		-k) K_VERSION=$2; shift 2;;
-		--k-version*) K_VERSION=${1#*=}; shift;;
+		--k-version=*) K_VERSION=${1#*=}; shift;;
 		--kmap=*) [ -n "${1#*=}" ] && KEYMAP=${1#*=}; shift;;
 		--lvm|-l) iLVM=y; shift;;
-		--misc-dir*) [ -n "${1#*=}" ] && MISC=${1#*=}; shift;;
-		--splash*) [ -n "${1#*=}" ] && SPLASH=${1#*=}; shift;;
+		--misc-dir=*) [ -n "${1#*=}" ] && MISC=${1#*=}; shift;;
+		--splash=*) [ -n "${1#*=}" ] && SPLASH=${1#*=}; shift;;
 		--toi) iTOI=y; shift;;
-		*) short_help; exit 0;;
+		-h|--help|*) usage; exit 0;;
 	esac
 done
 
@@ -98,8 +109,8 @@ esac
 echo ">>> building $INITRAMFS..."
 rm -rf $INITDIR || die "eek!"
 mkdir -p $INITDIR && cd $INITDIR || die "eek!"
-mkdir -p {{,s}bin,dev,etc/{modules,splash},mnt/tok,newroot,proc,root,sys,usr/{bin,sbin}} || die "eek!"
-mkdir -p lib64/{splash/cache,modules/$K_VERSION/{misc,kernel/{crypto,fs/nls}}} || die "eek!"
+mkdir -p {,s}bin dev proc root sys usr/{bin,sbin} newroot || die "eek!"
+mkdir -p lib64/splash/cache etc/{modules,splash} mnt/tok || die "eek!"
 ln -sf lib64 lib || die "eek!"
 
 cp -a /dev/{console,random,urandom,mem,null,tty,tty1,zero} dev/ || {
@@ -129,18 +140,16 @@ if [ -e "$BIN"/applets ]; then
 else 	sed -e 's|#\t/bin/busybox|\t/bin/busybox|' -i init || die "eek!"; fi
 
 if [ -n "$iAUFS" ]; then
-	MOD+=" kernel/fs/aufs misc/aufs.ko"
+	MOD+=" aufs"
 	cp -a /sbin/{,u}mount.aufs sbin/ || die "failed to copy *mount.aufs"
 	echo aufs > etc/modules/sqfsd || die "eek!"
-	unset iAUFS
-fi
+	unset iAUFS; fi
 
 if [ -n "$iGPG" ]; then
 	cp -a $BIN/gpg usr/bin/ || die "failed to copy gpg"
 	cp -ar $MISC/share usr/ || die "failed to copy $MISC/share"
 	cp -ar $MISC/.gnupg . || die "failed to copy $MISC/.gnupg"
-	unset iGPG
-fi
+	unset iGPG; fi
 
 if [ -n "$iLVM" ]; then
 	cp -a /sbin/lvm.static sbin/lvm || die "eek!"
@@ -149,61 +158,40 @@ if [ -n "$iLVM" ]; then
 		do ln -s lvm $lpv || die "eek!"
 	done
 	cd ..
-	unset iLVM
-fi
+	unset iLVM; fi
 
-for mod in $FS; do
-	if [ -e /lib/modules/$K_VERSION/kernel/fs/$mod ]; then
-	cp -ar /lib/modules/$K_VERSION/kernel/fs/$mod lib/modules/$K_VERSION/kernel/fs/${mod%*/} || \
-		die "mod copy failed"
-	fi
-	unset FS
-done
-
-for mod in $MOD; do
-	if [ -e /lib/modules/$K_VERSION/$mod ]; then
-	cp -ar /lib/modules/$K_VERSION/$mod lib/modules/$K_VERSION/${mod%/*} || die "mod copy failed"
-	fi
-	unset MOD
-done
+addmodule "$MOD" && unset MOD
 
 if [ -n "$FSCK" ]; then
 	for fs in $FSCK; do
 		cp -a /sbin/fsck.$fs sbin/
-		for lib in $(ldd /sbin/fsck.$fs|sed -e "s:li.*=>\ ::g" -e "s:\ (.*)::g"); do
-			cp -adH $lib lib/ || die "failed to copy $lib library"
-		done
+		for lib in $(ldd /sbin/fsck.$fs|sed -e "s:li.*=>\ ::g" -e "s:\ (.*)::g")
+			do cp -adH $lib lib/ || die "failed to copy $lib library"; done
 	done
-	unset FSCK
-fi
+	unset FSCK; fi
 
 for key in ${!MODULES[@]}; do
 	for grp in ${MODULES[$key]}; do
 		if [ -n "${grp#*=}" ]; then
-			for mod in ${grp#*=}; do
-				echo $mod >> etc/modules/${grp%=*}
-			done
+			for mod in ${grp#*=}
+				do echo $mod >> etc/modules/${grp%=*}; done
 		fi
 	done
-	unset MODULES
-done
+	unset MODULES; done
 
 if [ -n "$KEYMAP" ]; then 
 	cp -a "$KEYMAP" etc/ || die "failed to copy keymap"
-	unset KEYMAP
-fi
+	unset KEYMAP; fi
 
 [ -e "$FONT" ] && cp -a "$FONT" etc/
 
 if [ -n "$SPLASH" ]; then
 	if [ -n "$iTOI" ]; then
 		cp -a /sbin/tuxoniceui_text sbin/ || die "failed to copy toi helper"
-		unset iTOI
-	fi
+		unset iTOI; fi
 	cp -a /sbin/splash_util.static sbin/ || die "failed to copy splash_util.static"
 	cp -ar "$SPASH" etc/splash/ || die "splash themes does not exist"
-	unset SPLASH
-fi
+	unset SPLASH; fi
 
 find . -print0|cpio --null -ov --format=newc|$CMD > $INITRAMFS || die "eek!"
 
@@ -216,4 +204,3 @@ unset BIN
 unset CMD
 unset INITRAMFS
 unset MISC
-
diff --git a/mkifs-ll_bb b/mkifs-ll_bb
--- a/mkifs-ll_bb
+++ b/mkifs-ll_bb
@@ -1,12 +1,12 @@
 #!/bin/bash
-revision=0.3.2_p20110904
+revision=0.3.2_p20110906
 
-short_help() {
+usage() {
 	cat << EOF
   usage:
   ${0##*/} [-b|--build [-m|--minimal] [--uCl-arch=i386] ] [--kmap=map:kmap]
   -b, --build		build a static busybox.
-  -m, --minimal		build busybox with only the essential applets, default is to build all applets.
+  -m, --minimal		build busybox with minimal applets, default is to build all applets.
   -i, --install		install busybox with symliks to './bin', require -b|--build.
       --kmap=map:kmap	generate kmap keymap using map as input keymap.
       --uCl-arch=i386	ARCH string for uClibc build.		
@@ -15,7 +15,7 @@ short_help() {
 EOF
 }
 
-if [[ $# = 0 ]]; then short_help; exit 0; fi
+if [[ $# = 0 ]]; then usage; exit 0; fi
 
 while [[ $# > 0 ]]; do
 	case $1 in
@@ -27,7 +27,7 @@ while [[ $# > 0 ]]; do
 		--kmap=*) KBB=y; KEYMAP_IN=$(echo ${1#*=}|cut -d':' -f1)
 			KEYMAP_OUT=$(echo ${1#*=}|cut -d':' -f2); shift;;
 		-v|--version)  echo "version $revision"; exit 0;;
-		-h|--help|*) short_help; exit 0;;
+		-h|--help|*) usage; exit 0;;
 	esac
 done
 
@@ -79,25 +79,25 @@ build_busybox() {
 		-e "s|# CONFIG_SWITCH_ROOT is not set|CONFIG_SWITCH_ROOT=y|" \
 		-e "s|# CONFIG_TEST is not set|CONFIG_TEST=y|" \
 		-e "s|# CONFIG_TR is not set|CONFIG_TR=y|" \
-		-e "s|# CONFIG_WHICH is not set|CONFIG_WHICH=y|" -i .config || die "minimal cfg failed"
+		-e "s|# CONFIG_WHICH is not set|CONFIG_WHICH=y|" \
+		-i .config || die "minimal cfg failed"
 	else 
 		make defconfig || die "defcfg failed"
 		sed -e "s|# CONFIG_STATIC is not set|CONFIG_STATIC=y|" \
-		-e "s|# CONFIG_INSTALL_NO_USR is not set|CONFIG_INSTALL_NO_USR=y|" -i .config || die "cfg failed"
-	fi
+		-e "s|# CONFIG_INSTALL_NO_USR is not set|CONFIG_INSTALL_NO_USR=y|" \
+		-i .config || die "cfg failed"; fi
 
 	# For uClibc users, you need to adjust the cross compiler prefix properly (i386-uclibc-)
 	if [ -n "$UCL_ARCH" ]; then
-		sed -i -e "s|CONFIG_CROSS_COMPILER_PREFIX=\"\"|CONFIG_CROSS_COMPILER_PREFIX=\"$UCL_ARCH\"|" .config
-	fi
+	sed -e "s|CONFIG_CROSS_COMPILER_PREFIX=\"\"|CONFIG_CROSS_COMPILER_PREFIX=\"$UCL_ARCH\"|" \
+		-i .config || die "setting uClib ARCH failed"; fi
 	make && make busybox.links || die "bb build failed"
 }
 
 install_busybox() {
 	if [ -e "$TMP_DIR" ]; then
 		make install CONFIG_PREFIX="$TMP_DIR"/busybox
-		rm -rf /tmp/busybox
-	fi
+		rm -rf /tmp/busybox; fi
 	./applets/install.sh $BIN/ --symlinks
 }
 
@@ -106,15 +106,12 @@ build_keymap() {
 	dumpkeys > default_keymap || die "dumping keymap failed"
 	loadkeys $KEYMAP_IN || die "loading $KEMAP_IN failed"
 	if [ "$UNICODE" = "y" ]; then 
-		dumpkeys|loadkeys -u || die "unicode conversion failed"
-	fi
+		dumpkeys|loadkeys -u || die "unicode conversion failed"; fi
 	./busybox dumpkmap > $KEYMAP_OUT || die "keymap build failed"
 	# load back your keymap
 	loadkeys default_keymap && rm default_keymap || die "re-loading default keymap failed"
 	if [ "$(pwd)" != "$WORKDIR"/bin ]; then 
-		cp $KEYMAP_OUT $BIN/ || die "$KEYMAP_OUT copy failed"
-
-	fi
+		cp $KEYMAP_OUT $BIN/ || die "$KEYMAP_OUT copy failed"; fi
 	unset KEYMAP_IN
 	unset KEYMAP_OUT
 	unset UNICODE
@@ -127,20 +124,17 @@ if [ "${BBB}" = "y" ]; then
 	cp -a busybox $BIN/ || die "failed to copy bb binary"
 	cp busybox.links $BIN/applets || die "failed to copy applets"
 	unset CONFIG
-	unset IBB
-fi
+	unset IBB; fi
 
 if [ "${KBB}" = "y" ]; then
 	mkdir -p $BIN
 	[ "${BBB}" != "y" ] && cd $BIN || die "eek!"
 	build_keymap
-	unset KBB
-fi
+	unset KBB; fi
 
 if [ "${BBB}" = "y" ]; then
 	cd ${PORTDIR:-/usr/portage}/sys-apps/busybox || die "eek"
 	ebuild $BBT.ebuild clean || die "eek"
 	cd $WORKDIR || die "eek!"
 	unset BBB
-	unset BBT
-fi
+	unset BBT; fi
