mkifs-ll: v0.5.0 version bump (raid support)

diff --git a/mkifs-ll b/mkifs-ll
--- a/mkifs-ll
+++ b/mkifs-ll
@@ -1,6 +1,6 @@
 #!/bin/bash
-# $Id: mkinitramfs-ll/mkifs-ll[.bash],v 0.4.1 2011/12/20 -tclover Exp $
-revision=0.4.1
+# $Id: mkinitramfs-ll/mkifs-ll[.bash],v 0.5.0 2011/12/23 -tclover Exp $
+revision=0.5.0
 
 usage() {
   cat <<-EOF
@@ -26,8 +26,9 @@ usage() {
      --msqfsd :<mod>    colon separated list of kernel modules to add to sqfsd group
      --mremdev :<mod>   colon separated list of kernel modules to add to remdev group
      --mtuxonice :<mod> colon separated list of kernel modules to add to tuxonice group
-  -t|--toi              adds tuxonice support for splash, require tuxoniceui_text binary
+  -t|--toi              add tuxonice support for splash, require tuxoniceui_text binary
   -s|--sqfsd            add aufs(+squashfs modules +{,u}mount.aufs binaries) support
+  -r|--raid             add RAID support, copy /etc/mdadm.conf and mdadm binary
   -u|--usage            print this help/usage and exit
   -v|--version          print version string and exit
 
@@ -57,9 +58,9 @@ addnodes() {
 }
 
 [[ $# = 0 ]] && info "initramfs will be build with only LUKS support."
-opt=$(getopt -o ab:c:e:fgk:lm:stuvy:B:M:S:W: --long all,bin:,bindir:comp:,ev:,font:,keymap: \
+opt=$(getopt -o ab:c:e:fgk:lm:rstuvy:B:M:S:W: --long all,bin:,bindir:comp:,ev:,font:,keymap: \
 	  --long gpg:,mboot:,mdep:,mgpg:msqfsd:,mremdev:,mtuxonice,sqfsd,toi,usage,version \
-	  --long lvm,miscdir:,workdir:,kv: -n ${0##*/} -- "$@" || usage && exit 0)
+	  --long lvm,miscdir:,workdir:,kv:,raid -n ${0##*/} -- "$@" || usage && exit 0)
 eval set -- "$opt"
 [[ -z "${opts[*]}" ]] && declare -A opts
 while [[ $# > 0 ]]; do
@@ -67,6 +68,7 @@ while [[ $# > 0 ]]; do
 		-u|--usage) usage; exit 0;;
 		-v|--version) echo "${0##*/}-$revision"; exit 0;;
 		-a|--all) opts[sqfsd]=y; opts[gpg]=y; opts[lvm]=y; opts[toi]=y; shift;;
+		-r|--raid) opts[raid]=y; shift;;
 		-s|--sqfsd) opts[sqfsd]=y; shift;;
 		-b|--bin) opts[bin]+=:${2}; shift 2;;
 		-c|--comp) opts[comp]="${2}"; shift 2;;
@@ -164,6 +166,10 @@ else sed -e 's|#\t/bin/busybox|\t/bin/busybox|' -i init || die "eek!"
 		do ln -sf lvm $lpv || die "eek!"
 	done
 	cd ..
+}
+
+[[ -n "${opts[raid]}" ]] && { opts[bin]+=:mdadm.static:mdadm
+	cp /etc/mdadm.conf etc/ &>/dev/null || warn "failed to copy /etc/mdadm.conf"
 }
 
 addmodule() {
