mkifs-ll{,.conf}: minor fixes and editing

diff --git a/mkifs-ll b/mkifs-ll
--- a/mkifs-ll
+++ b/mkifs-ll
@@ -1,5 +1,5 @@
 #!/bin/zsh
-revision=0.3.5_p20111019
+revision=0.3.5_p20111022
 
 usage() {
   cat << EOF
@@ -45,17 +45,18 @@ EOF
 
 error() { echo -ne "\e[1;31m* \e[0m$@\n"; }
 info() 	{ echo -ne "\e[1;32m* \e[0m$@\n"; }
+warn() 	{ echo -ne "\e[1;33m* \e[0m$@\n"; }
 die() { error $@; exit 1; }
 
 addnodes() {
-	[ -c dev/console ] 	|| mknod dev/console c 5 1 	|| die "eek!"
-	[ -c dev/urandom ] 	|| mknod dev/urandom c 1 9 	|| die "eek!"
-	[ -c dev/random ] 	|| mknod dev/random c 1 8 	|| die "eek!"
-	[ -c dev/mem ] 		|| mknod dev/mem c 1 1 		|| die "eek!"
-	[ -c dev/null ] 	|| mknod dev/null c 1 3 	|| die "eek!"
-	[ -c dev/tty ] 		|| mknod dev/tty c 5 0 		|| die "eek!"
-	[ -c dev/tty1 ] 	|| mknod dev/tty1 c 4 1 	|| die "eek!"
-	[ -c dev/zero ] 	|| mknod dev/zero c 1 5 	|| die "eek!"
+	[ -c dev/console ] || mknod dev/console c 5 1 || die "eek!"
+	[ -c dev/urandom ] || mknod dev/urandom c 1 9 || die "eek!"
+	[ -c dev/random ] || mknod dev/random c 1 8 || die "eek!"
+	[ -c dev/mem ] || mknod dev/mem c 1 1 || die "eek!"
+	[ -c dev/null ] || mknod dev/null c 1 3 || die "eek!"
+	[ -c dev/tty ] || mknod dev/tty c 5 0 || die "eek!"
+	[ -c dev/tty1 ] || mknod dev/tty1 c 4 1 || die "eek!"
+	[ -c dev/zero ] || mknod dev/zero c 1 5 || die "eek!"
 }
 
 [[ $# = 0 ]] && info "initramfs will be build with only LUKS support."
@@ -118,12 +119,12 @@ cp -a $BIN/busybox bin/ || die "failed to copy busybox"
 
 if [[ -e $BIN/applets ]] {
 	cp -a $BIN/applets etc/
-	for app ($(< etc/applets)); do ln -sf bin/busybox .$app || die "eek!"; done 
-	} else { sed -e 's|#\t/bin/busybox|\t/bin/busybox|' -i init || die "eek!" }
+	for app ($(< etc/applets)) ln -sf bin/busybox .$app || die "eek!" 
+} else { sed -e 's|#\t/bin/busybox|\t/bin/busybox|' -i init || die "eek!" }
 
 if [[ -n $iAUFS ]] {
 	for fs ({au,squash}fs) 
-	do [[ -n ${MODULES[(r)$fs,sqfsd]} ]] || MODULES[sqfsd]+=",$fs"; done
+		[[ -z ${MODULES[(r)$fs,sqfsd]} ]] && MODULES[sqfsd]+=",$fs"
 	cp -a /sbin/{,u}mount.aufs sbin/ || die "failed to copy *mount.aufs"
 	unset iAUFS }
 
@@ -131,62 +132,67 @@ if [[ -n $iGPG ]] {
 	cp -a $BIN/gpg usr/bin/ || die "failed to copy gpg"
 	cp -ar $MISC/share usr/ || die "failed to copy $MISC/share"
 	cp -ar $MISC/.gnupg . || die "failed to copy $MISC/.gnupg"
-	unset iGPG }
+	unset iGPG
+}
 
 if [[ -n $iLVM ]] {
 	cp -a /sbin/lvm.static sbin/lvm || die "eek!"
 	for lpv ({vg,pv,lv}{change,create,re{move,name},s{,can}} {lv,vg}reduce lvresize vgmerge)
 	do ln -sf sbin/{lvm,$lpv} || die "eek!"; done
-	unset iLVM }
+	unset iLVM 
+}
 
 addmodule() {
-	for mod (/lib/modules/$K_VERSION/**/*$@.(ko|o)); do
-	if [[ ! -e $mod ]] { info "$mod does not exist"; return 1 
-	} else { mkdir -p .$mod:h && cp -ar $mod .$mod:h/ || die "$mod copy failed" }; done
+	for mod (/lib/modules/$K_VERSION/**/*$@.(ko|o))
+		if [[ ! -e $mod ]] { info "$mod does not exist"; return 1 
+		} else { mkdir -p .$mod:h && cp -ar $mod .$mod:h/ || die "$mod copy failed" }
 }
 
 set EXTENDED_GLOB
 set NULL_GLOB
 set NOMATCH
 
-for module (${(pws:,:)MODS}) addmodule $module; unset MODS
-for grp (boot gpg remdev sqfsd tuxonice); do
-	if [[ -n $MODULES[$grp] ]] {
-		for module (${(pws:,:)MODULES[$grp]})
-		do addmodule $module && echo $module >> etc/modules/$grp; done }
-done
+for module (${(pws:,:)MODS}) addmodule $module
+unset MODS
+for grp (boot gpg remdev sqfsd tuxonice) 
+	if [[ -n $MODULES[$grp] ]] { 
+		for module (${(pws:,:)MODULES[$grp]}) 
+		addmodule $module && echo $module >> etc/modules/$grp }
 unset MODULES
 
 if [[ -n $FSCK ]] {
-	for fs (${(pws:,:)FSCK[*]}); do 
+	for fs (${(pws:,:)FSCK[*]}) 
 		if [[ -e /sbin/fsck.$fs ]] { 
 			cp -aL /sbin/fsck.$fs sbin/
 			if [[ "$(ldd /sbin/fsck.$fs)" != *"not a dynamic executable" ]] {
 				for lib ($(ldd /sbin/fsck.$fs|sed -e "s:li.*=>\ ::g" -e "s:\ (.*)::g"))
-				do cp -adH $lib lib/ || die "failed to copy $lib library"; done }
+					cp -adH $lib lib/ || die "failed to copy $lib library" 
+			} else { info "fsck.$fs is a static binary." }
 		} else { info "/sbin/fsck.$fs binary doesn't exist" }
-	done
-	unset FSCK }
+	unset FSCK
+}
 
 if [[ -n $KEYMAPS ]] { 
-	for keymap (${(pws:,:)KEYMAPS}); do 
-		[[ -e $keymap ]] && cp -a $keymap etc/ || die "failed to copy $keymap keymap"; done
-	unset KEYMAPS }
+	for keymap (${(pws:,:)KEYMAPS}) 
+		[[ -e $keymap ]] && cp -a $keymap etc/ || warn "failed to copy $keymap keymap"
+	unset KEYMAPS
+}
 
 if [[ -n $FONTS ]] { 
-	for font (${(pws:,:FONTS}); do 
-		[[ -e $font ]] && cp -a $font etc/ || die "failed to copy $font font"; done 
-		unset FONTS }
+	for font (${(pws:,:FONTS})
+		[[ -e $font ]] && cp -a $font etc/ || warn "failed to copy $font font" 
+	unset FONTS 
+}
 
 if [[ -n $SPLASHS ]] { 
 	if [[ -n $iTOI ]] {
 		cp -a /sbin/tuxoniceui_text sbin/ || die "failed to copy toi helper"
 		unset iTOI }
 	cp -a /sbin/splash_util.static sbin/ || die "failed to copy splash_util.static"
-	for splash (${(pws:,:SPLASHS}); do
-		[[ -e $splash ]] && cp -ar $splash etc/splash/ || die "splash themes does not exist"
-	done
-	unset SPLASH }
+	for splash (${(pws:,:SPLASHS})
+		[[ -e $splash ]] && cp -ar $splash etc/splash/ || warn "splash themes does not exist"
+	unset SPLASHS
+}
 
 find . -print0|cpio --null -ov --format=newc|${=CMD} > $INITRAMFS || die "eek!"
 
