mkifs-ll{,.conf}: update and fix, now the zsh scripts works perfectly fine. there are new things that tagged along with this commit: now SPLASHS, FONTS, KEYMPAS are comma separated lists, meaning one can add more than a single splash, font and keymap! i will add that to the master (bash) script later.

diff --git a/mkifs-ll b/mkifs-ll
--- a/mkifs-ll
+++ b/mkifs-ll
@@ -1,9 +1,9 @@
 #!/bin/zsh
-revision=0.3.5_p20111017
+revision=0.3.5_p20111019
 
 usage() {
-	cat << EOF
-   usage: ${0##*/} [OPTIONS...]
+  cat << EOF
+  usage: ${0##*/} [OPTIONS...]
       --aufs		adds aufs[2] support to the initramfs for (aufs2+squashfs).
   -e, --e-version=<str>	append <str> extra version after k-version to the initramfs.
   -k, --k-version=<str>	build an initramfs for 'k-version=\${KV:-\$(uname -r)}' kernel version.
@@ -32,24 +32,20 @@ usage() {
   
   <str> 	string
   <font>	full path to font, easy to include one into 'bin' directory and add its name
-  		into \${FONT:=\$BIN/<name>} definition into mkifs-ll.conf
+  			into \${FONT:=\$BIN/<name>} definition into mkifs-ll.conf
   <km-x86.bin>	same as above for KEYMMAP variable.
   <fs> 		file system e.g. xfs, default is 'btrfs jfs reiserfs squashfs xfs reiser4'.
   <theme>	full path to splash 'theme'.
   <fs> 		file sytem.
   bin		full path to directory with the necessary binaries to build an initramfs.
   misc		second full path to directory with extra necessary files.
-  --*=		all arguments will use default value definied in mkifs-ll.conf if empty.
+  --<arg>=	all arguments will use default value definied in mkifs-ll.conf if empty.
 EOF
 }
 
 error() { echo -ne "\e[1;31m* \e[0m$@\n"; }
 info() 	{ echo -ne "\e[1;32m* \e[0m$@\n"; }
-
-die() {
-	error "$@"
-	exit 1
-}
+die() { error $@; exit 1; }
 
 addnodes() {
 	[ -c dev/console ] 	|| mknod dev/console c 5 1 	|| die "eek!"
@@ -62,62 +58,37 @@ addnodes() {
 	[ -c dev/zero ] 	|| mknod dev/zero c 1 5 	|| die "eek!"
 }
 
-addsplsh() {
-	if [[ -n "$iTOI" ]] {
-		cp -a /sbin/tuxoniceui_text sbin/ || die "failed to copy toi helper"
-		unset iTOI }
-	cp -a /sbin/splash_util.static sbin/ || die "failed to copy splash_util.static"
-	cp -ar "$SPLASH" etc/splash/ || die "splash themes does not exist"
-}
-
-addmodule() {
-	for mod in $@; do
-		local module=$(find /lib/modules/$K_VERSION -name $mod.ko)
-		if [[ -z $module ]] { info "$mod does not exist"; return 1 
-		} else { mkdir -p .$module:h
-		cp -ar $module .$module:h/ || die "$module copy failed" }
-	done
-}
-
-modules() {
-	for grp in boot gpg remdev sqfsd tuxonice; do
-		if [[ -n ${MODULES[$grp]} ]] {
-			for mod in ${(pws:,:)MODULES[$grp]}
-			do addmodule $mod && echo $mod >> etc/modules/$grp; done }
-	done
-}
-
-[ $# = 0 ] && info "initramfs will be build with only LUKS support."
+[[ $# = 0 ]] && info "initramfs will be build with only LUKS support."
 
 while [[ $# > 0 ]]; do
 	case $1 in
 		-v|--version) echo "version $revision"; exit 0;;
 		--aufs) iAUFS=y; shift;;
-		--bin-dir=*) [ -n "${1#*=}" ] && BIN=${1#*=}; shift;;
-		--comp-cmd=*) [ -n "${1#*=}" ] && CMD=${1#*=}; shift;;
+		--bin-dir=*) [[ -n ${1#*=} ]] && BIN=${1#*=}; shift;;
+		--comp-cmd=*) [[ -n ${1#*=} ]] && CMD=${1#*=}; shift;;
 		-e) E_VERSION=$2; shift 2;;
-		--e-version=*) [ -n "${1#*=}" ] && E_VERSION=${1#*=}; shift;;
-		--font=*) [ -n "${1#*=}" ] && FONT=${1#*=}; shift;;
+		--e-version=*) E_VERSION=${1#*=}; shift;;
+		--font=*) [[ -n ${1#*=} ]] && FONTS+=",${1#*=}"; shift;;
 		-f|--full) iAUFS=y; iGPG=y; iLVM=y, iTOI=y; shift;;
-		--mod=*) [ -n "${1#*=}" ] && MOD=${1#*=}; shift;;
-		--fsck=*) [ -n "${1#*=}" ] && FSCK=${1#*=}; shift;;
+		--mod=*) MOD+=",${1#*=}"; shift;;
+		--fsck=*) FSCK+=",${1#*=}"; shift;;
 		-g|--gpg) iGPG=y; shift;;
 		--prefix=*) PREFIX=${1#*=}; shift;; 
 		-k) K_VERSION=$2; shift 2;;
 		--k-version=*) K_VERSION=${1#*=}; shift;;
-		--kmap=*) [ -n "${1#*=}" ] && KEYMAP=${1#*=}; shift;;
+		--kmap=*) [[ -n ${1#*=} ]] && KEYMAPS+=",${1#*=}"; shift;;
 		--lvm|-l) iLVM=y; shift;;
-		--misc-dir=*) [ -n "${1#*=}" ] && MISC=${1#*=}; shift;;
-		--splash=*) [ -n "${1#*=}" ] && SPLASH=${1#*=}; shift;;
+		--misc-dir=*) [[ -n ${1#*=} ]] && MISC=${1#*=}; shift;;
+		--splash=*) [[ -n ${1#*=} ]] && SPLASHS+=",${1#*=}"; shift;;
 		--toi) iTOI=y; shift;;
 		-h|--help|*) usage; exit 0;;
 	esac
 done
 
 typeset -A MODULES
-[ -f ./mkifs-ll.conf ] && . ./mkifs-ll.conf
+[[ -f ./mkifs-ll.conf ]] && source ./mkifs-ll.conf
 : 	${K_VERSION:=$(uname -r)}
-[ -n "$E_VERSION" ] && E_VERSION=-$E_VERSION
+[[ -n $E_VERSION ]] && E_VERSION=-$E_VERSION
 :	${INITRAMFS:=/boot/${PREFIX:-initrd-}$K_VERSION$E_VERSION.cpio.xz}
 :	${WORKDIR:=$(pwd)}
 :	${MISC:=$WORKDIR/misc}
@@ -125,7 +96,7 @@ typeset -A MODULES
 :	${BIN:=$WORKDIR/bin}
 :	${CMD:=xz -9 --check=crc32}
 
-case ${CMD%%\ *} in
+case ${(A)CMD[(w)1} in
 	bzip2)	INITRAMFS=${INITRAMFS/.xz/.bz2};;
 	gzip) 	INITRAMFS=${INITRAMFS/.xz/.gz};;
 	lzma)	INITRAMFS=${INITRAMFS/.xz/.lzma};;
@@ -144,57 +115,77 @@ cp -a $WORKDIR/init . || die "failed to copy init"
 cp -a /sbin/{cryptsetup,v86d} sbin/ || die "faied to copy v86d"
 cp -a $BIN/busybox bin/ || die "failed to copy busybox"
 
-if [[ -e "$BIN"/applets ]] {
+if [[ -e $BIN/applets ]] {
 	cp -a $BIN/applets etc/
-	for app in $(< etc/applets); do
-	case ${app%/*} in
-		/bin) cd bin && ln -sf busybox ${app##*/} && cd .. || die "eek!";;
-		/sbin) cd sbin && ln -sf ../bin/busybox ${app##*/} && cd .. || die "eek!";;
-		*) ln -sf bin/busybox ${app#*/} || die "eek";;
-	esac
-	done } else { sed -e 's|#\t/bin/busybox|\t/bin/busybox|' -i init || die "eek!" }
+	for app ($(< etc/applets)); do ln -sf bin/busybox .$app || die "eek!"; done 
+	} else { sed -e 's|#\t/bin/busybox|\t/bin/busybox|' -i init || die "eek!" }
 
-if [[ -n "$iAUFS" ]] {
-	for fs in {au,squash}fs
-	do [[ -n ${MODULES[(r)$fs,sqfsd]} ]] || MODULES[sqfsd]+=",$fs"; done
+if [[ -n $iAUFS ]] {
+	for fs ({au,squash}fs) 
+		do [[ -n ${MODULES[(r)$fs,sqfsd]} ]] || MODULES[sqfsd]+=",$fs"; done
 	cp -a /sbin/{,u}mount.aufs sbin/ || die "failed to copy *mount.aufs"
 	unset iAUFS }
 
-if [[ -n "$iGPG" ]] {
+if [[ -n $iGPG ]] {
 	cp -a $BIN/gpg usr/bin/ || die "failed to copy gpg"
 	cp -ar $MISC/share usr/ || die "failed to copy $MISC/share"
 	cp -ar $MISC/.gnupg . || die "failed to copy $MISC/.gnupg"
 	unset iGPG }
 
-if [[ -n "$iLVM" ]] {
+if [[ -n $iLVM ]] {
 	cp -a /sbin/lvm.static sbin/lvm || die "eek!"
-	cd sbin
-	for lpv in {vg,pv,lv}{change,create,re{move,name},s{,can}} {lv,vg}reduce lvresize vgmerge
-		do ln -s lvm $lpv || die "eek!"
-	done
-	cd ..
+	for lpv ({vg,pv,lv}{change,create,re{move,name},s{,can}} {lv,vg}reduce lvresize vgmerge)
+		do ln -sf sbin/{lvm,$lpv} || die "eek!"; done
 	unset iLVM }
 
-addmodule ${(pws:,:)MOD} && unset MOD
+addmodule() {
+	for mod ($@); do
+		local module=$(find /lib/modules/$K_VERSION -name $mod.ko)
+		if [[ -z $module ]] { info "$mod does not exist"; return 1 
+		} else { mkdir -p .$module:h
+		cp -ar $module .$module:h/ || die "$module copy failed" }
+	done
+}
+modules() {
+	for grp boot gpg remdev sqfsd tuxonice; do
+		if [[ -n $MODULES[$grp] ]] {
+			for mod (${(pws:,:)MODULES[$grp]})
+				do addmodule $mod && echo $mod >> etc/modules/$grp; done }
+	done
+}
+addmodule ${(pws:,:)MODS} && unset MODS
 modules && unset MODULES
 
 if [[ -n $FSCK ]] {
-	for fs in ${(pws:,:)FSCK}; do
+	for fs (${(pws:,:)FSCK[*]}); do
 		cp -aL /sbin/fsck.$fs sbin/
 		if [[ "$(ldd /sbin/fsck.$fs)" != *"not a dynamic executable" ]] {
-		for lib in $(ldd /sbin/fsck.$fs|sed -e "s:li.*=>\ ::g" -e "s:\ (.*)::g")
+		for lib ($(ldd /sbin/fsck.$fs|sed -e "s:li.*=>\ ::g" -e "s:\ (.*)::g"))
 			do cp -adH $lib lib/ || die "failed to copy $lib library"; done }
 	done
 	unset FSCK }
 
-if [[ -n "$KEYMAP" ]] { 
-	cp -a "$KEYMAP" etc/ || die "failed to copy keymap"
-	unset KEYMAP }
+if [[ -n $KEYMAPS ]] { 
+	for keymap (${(pws:,:)KEYMAPS}); do 
+		[[ -e $keymap ]] && cp -a $keymap etc/ || die "failed to copy $keymap keymap"; done
+	unset KEYMAPS }
 
-if [[ -e "$FONT" ]] { cp -a "$FONT" etc/ && unset FONT }
-if [[ -n "$SPLASH" ]] { addsplash && unset SPLASH }
+if [[ -n $FONTS ]] { 
+	for font (${(pws:,:FONTS}); do 
+		[[ -e $font ]] && cp -a $font etc/ || die "failed to copy $font font"; done 
+		unset FONTS }
 
-find . -print0 | cpio --null -ov --format=newc | $CMD > "$INITRAMFS" || die "eek!"
+if [[ -n $SPLASHS ]] { 
+	if [[ -n $iTOI ]] {
+		cp -a /sbin/tuxoniceui_text sbin/ || die "failed to copy toi helper"
+		unset iTOI }
+	cp -a /sbin/splash_util.static sbin/ || die "failed to copy splash_util.static"
+	for splash (${(pws:,:SPLASHS}); do
+		[[ -e $splash ]] && cp -ar $splash etc/splash/ || die "splash themes does not exist"
+	done
+	unset SPLASH }
+
+find . -print0|cpio --null -ov --format=newc| ${=CMD} > $INITRAMFS || die "eek!"
 
 echo ">>> $INITRAMFS initramfs built"
 
