mkifs-ll* init sqfsd/sdr[|sqfsd-rebuild]: important fix for mkifs-ll because of a typo, every binary have been copied from live system instead of copying first from $BINDIR. I have noticed it by rebooting and not being able to use gpg!

diff --git a/mkifs-ll b/mkifs-ll
--- a/mkifs-ll
+++ b/mkifs-ll
@@ -8,12 +8,12 @@ usage() {
   -e, --e-version=<str>  append <str> extra version after k-version to the initramfs
   -k, --k-version=<str>  build an initramfs for kernel '--k-version=\$(uname -r)'
       --font=<font>      collon seperated list of  font(s) to include to the initramfs
-  -f, --full             shor form of '--aufs --bin-dir --font --lvm --gpg --misci --toi'
-      --k-module=<mod>   collon seperated list of kernel modules to include.
+  -f, --full             short forme/hand of '--aufs --font --lvm --gpg --toi'
+      --k-module=<mod>   collon seperated list of kernel modules to include
       --binary=<bins>    collon seperated list of binaries to include in the initramfs
-      --bindir=bin       include binaries from \$BINDIR (busybox/gpg)
+      --bindir=bin       include binaries from \$BINDIR (busybox/applets/gpg)
       --comp-cmd=cmd     compression command to use to build initramfs, default is xz
-  -g, --gpg              adds GnuPG support, require a static gnupg-1.4/options.skel
+  -g, --gpg              adds GnuPG support, require a static gnupg-1.4.x/options.skel
       --prefix=vmlinuz.  prefix scheme to name the initramfs default is 'initrd-'
       --keymap=kmx86.bin collon seperated list of keymap(s) to include in the initramfs
   -l, --lvm              adds LVM2 support, require a static sys-fs/lvm2 build
@@ -37,7 +37,7 @@ error() { print -P "%B%F{red}*%b%f $@"; }
 info()  { print -P "%B%F{green}*%b%f $@"; }
 warn()  { print -P "%B%F{red}*%b%f $@"; }
 die()   { error $@; exit 1; }
-alias die='die "%F{yellow}%1x:%U${(%):-%I:%N}:%u%f" $@'
+alias die='die "%F{yellow}%1x:%U${(%):-%I}:%u%f" $@'
 
 addnodes() {
 	[ -c dev/console ] || mknod dev/console c 5 1 || die "eek!"
@@ -201,8 +201,8 @@ bincp() {
 }
 
 for bin (${(pws,:,)BINARIES})
-	if [[ -x $BINDIRDIR/$bin:t ]] { 
-		cp $BINDIR/$bin:t ./$bin:h || die "failed to copy $bin"
+	if [[ -x $BINDIR/${bin##*/} ]] { 
+		cp $BINDIR/${bin##*/} ./$bin:h || die "failed to copy $bin"
 	} elif [[ -x /$bin ]] { bincp /$bin
 	} else { bincp $(which $bin) }
 
