sqfsd/sqfsd-rebuild aka sdr revision bump to v0.3.5_p20111023 following previous devel commit...with already a fix(!): Lets say the second bottle neck that prevented to use this script in cron job was thrown away. Rebuilding squashed dirs based on a offest based was introduced on the previous commit. This one attempt to fix the failure to copy cp binary and its related libraries when rebuilding a squashed dir. I would like to have those two feature so I can add the script in cron and forget about it.

diff --git a/sqfsd/sqfsd-rebuild b/sqfsd/sqfsd-rebuild
--- a/sqfsd/sqfsd-rebuild
+++ b/sqfsd/sqfsd-rebuild
@@ -72,8 +72,13 @@ squashed() {
 		|| die "failed to mount $dir.sfs img."
 		if [[ -n "$EXT" ]]; then # now you can up[date] or rm squashed dir.
 			case $EXT in
-				rm) rm -rf /$dir/*;;
-				up) cp -aru "$sqfsdir/$dir"/ro/* /$dir;;
+				rm) rm -rf /$dir/* || die "failed to clean up $sqfsdir/$dir.";;
+				up) echo >/tmp/sdr
+					cp -aru $sqfsdir/$dir/ro/* /$dir/ 2>>/tmp/sdr
+					[[ $? ]] || for file in $(sed -e "s|.*\`||g" -e "s|':.*||g" /tmp/sdr)
+						do cp -a $sqfsdir/$dir/ro/${file/$dir} /tmp/ && \
+						mv /tmp/${file##*/} ${file%/*}/ || info "failed to move $file."; done
+					;;
 				*) info "nothing to do, usage is [up|rm].";;
 			esac
 		fi
