build/busybox minor update

diff --git a/build/busybox b/build/busybox
--- a/build/busybox
+++ b/build/busybox
@@ -30,7 +30,8 @@ die() {
 	exit 1
 }
 
-:	${CDIR:=$(pwd)}
+:	${WORKDIR:=$(pwd)}
+. 	$WORKDIR/misc/initramfs-ll.conf
 
 build_busybox() {
 	. /etc/make.conf
@@ -88,7 +89,7 @@ install_busybox() {
 		make install CONFIG_PREFIX="$TMP_DIR"/busybox
 		rm -rf /tmp/busybox
 	fi
-	./applets/install.sh $CDIR/bin/ --symlinks
+	./applets/install.sh $WORKDIR/bin/ --symlinks
 }
 
 build_keymap() { 
@@ -101,8 +102,8 @@ build_keymap() {
 	./busybox dumpkmap > $KEYMAP_OUT || die "keymap build failed"
 	# load back your keymap
 	loadkeys default_keymap && rm default_keymap || die "re-loading default keymap failed"
-	if [ "$(pwd)" != "$CDIR"/bin ]; then 
-		cp $KEYMAP_OUT $CDIR/bin/ || die "$KEYMAP_OUT copy failed"
+	if [ "$(pwd)" != "$WORKDIR"/bin ]; then 
+		cp $KEYMAP_OUT $WORKDIR/bin/ || die "$KEYMAP_OUT copy failed"
 
 	fi
 	unset KEMAP_IN
@@ -114,15 +115,15 @@ if [ "${BBB}" = "y" ]; then
 	mkdir -p bin
 	build_busybox
 	[ "$IBB" = "y" ] && install_busybox
-	cp -a busybox $CDIR/bin/ || die "eek!"
-	#cp applets $CDIR/bin/ || die "eek!"
+	cp -a busybox $WORKDIR/bin/ || die "eek!"
+	#cp applets $WORKDIR/bin/ || die "eek!"
 	unset CONFIG
 	unset IBB
 fi
 
 if [ "${KBB}" = "y" ]; then
 	mkdir -p bin
-	[ "${BBB}" = "y" ] || cd $CDIR/bin/ || die "eek!"
+	[ "${BBB}" = "y" ] || cd $WORKDIR/bin/ || die "eek!"
 	build_keymap
 	unset KBB
 fi
@@ -130,9 +131,9 @@ fi
 if [ "${BBB}" = "y" ]; then
 	cd ${PORTDIR:-/usr/portage}/sys-apps/busybox || die "eek"
 	#ebuild $BBT.ebuild clean || die "eek"
-	cd $CDIR || die "eek!"
+	cd $WORKDIR || die "eek!"
 	unset BBB
 	unset BBT
 fi
-	unset CDIR
+	unset WORKDIR
 exit 0
