build/busybox the same goes for the previous

diff --git a/build/busybox b/build/busybox
--- a/build/busybox
+++ b/build/busybox
@@ -93,7 +93,7 @@ install_busybox() {
 		make install CONFIG_PREFIX="$TMP_DIR"/busybox
 		rm -rf /tmp/busybox
 	fi
-	./applets/install.sh $WORKDIR/bin/ --symlinks
+	./applets/install.sh $BIN/ --symlinks
 }
 
 build_keymap() { 
@@ -107,7 +107,7 @@ build_keymap() {
 	# load back your keymap
 	loadkeys default_keymap && rm default_keymap || die "re-loading default keymap failed"
 	if [ "$(pwd)" != "$WORKDIR"/bin ]; then 
-		cp $KEYMAP_OUT $WORKDIR/bin/ || die "$KEYMAP_OUT copy failed"
+		cp $KEYMAP_OUT $BIN/ || die "$KEYMAP_OUT copy failed"
 
 	fi
 	unset KEMAP_IN
@@ -119,8 +119,8 @@ if [ "${BBB}" = "y" ]; then
 	mkdir -p $BIN
 	build_busybox
 	[ "$IBB" = "y" ] && install_busybox
-	cp -a busybox $WORKDIR/bin/ || die "eek!"
-	#cp applets $WORKDIR/bin/ || die "eek!"
+	cp -a busybox $BIN/ || die "eek!"
+	#cp applets $BIN/ || die "eek!"
 	unset CONFIG
 	unset IBB
 fi
