build/initramfs-ll minor fix: previous version was working with that line, do not ask why.

diff --git a/build/initramfs-ll b/build/initramfs-ll
--- a/build/initramfs-ll
+++ b/build/initramfs-ll
@@ -143,7 +143,7 @@ done
 
 for mod in $MOD; do
 	if [ -e /lib/modules/$K_VERSION/$mod ]; then
-	cp -ar /lib/modules/$K_VERSION/$mod lib/modules/$K_VERSION/${mod%*/} || die "mod copy failed"
+	cp -ar /lib/modules/$K_VERSION/$mod lib/modules/$K_VERSION/${mod%/*} || die "mod copy failed"
 	fi
 	unset MOD
 done
@@ -189,4 +189,6 @@ unset INITDIR
 unset BIN
 unset CMD
 unset INITRAMFS
+unset MISC
+exit0
 
