hooks/{btrfs,zfs,zram}: 0.19.0 version bump (Added colors support)

diff --git a/hooks/zfs b/hooks/zfs
--- a/hooks/zfs
+++ b/hooks/zfs
@@ -2,7 +2,7 @@
 # $Header: mkinitramfs-ll/hooks/zfs                      Exp $
 # $Author: (c) 2011-2015 -tclover <tokiclover@gmail.com> Exp $
 # $License: 2-clause/new/simplified BSD                  Exp $
-# $Version: 0.18.0 2015/01/20 12:33:03                   Exp $
+# $Version: 0.19.0 2015/02/20 12:33:03                   Exp $
 #
 
 set +e +x
@@ -15,7 +15,7 @@ source $LIBDIR/helpers   || return
 # @USAGE: <env> <group> <device> <key> <zpool-options>
 dozfs() {
 	echo $$ >/run/${0##*/}.pid
-	local bin
+	local bin name=zfs
 	$ECK && for bin in zfs zpool; do 
 		debug -d bck $bin
 	done
@@ -34,9 +34,9 @@ dozfs() {
 	debug -d _modprobe zfs
 	local _pool="${_vol%/*}"
 
-	if ! zpool list -H $_pool >/dev/null 2>&1; then
+	if ! zpool list -H $_pool >$NULL 2>&1; then
 		if yesno "$_vdev"; then
-			error "zfs: No $_pool pool found"
+			error "No $_pool pool found"
 			return
 		fi
 		debug -d stk "$_KEY"
@@ -49,7 +49,7 @@ dozfs() {
 	if [ "$_grp" = 1 ]; then
 		zfs mount | grep -q "$_vol" || debug -d zfs mount -vO -a
 	else
-		zfs list  | grep -q "$_vol" || die "zfs: $_vol volume not found"
+		zfs list  | grep -q "$_vol" || die "$_vol volume not found"
 		_vol=/dev/zvol/$_vol
 	fi
 	rm /run/${0##*/}.pid
